### ISSUE TITLE
Sample description

### ISSUE THREAD

**Issue by Trickx** [eclipse/paho.mqtt.golang#132]
I'm missing descriptions for given usage examples.
Most examples under cmd folder do not provide any details about their purpose.
I'm looking for an example on how to maintain a connection to periodically publish sensor data from a golang daemon.
I'm not loosing the connection but publication of data stops after a while without any errors in my implementation.

**Comment by alsm** [comment]
Do you have a link to the code you're working on? It'd probably be easier to see how you're trying to do and I could then update the samples.

**Comment by Trickx** [comment]
Yes, please have a look at
https://github.com/Trickx/SmartPi/blob/master/src/readout/mqtt.go
This is the main MQTT loop.
`publishMQTTReadouts` is called periodically.
The function shall reconnect if the connetion to the MQTT broker was lost
and publish some measurement results.

I had the problem of loosing the connection without any error messages.
A reconnect was not triggered but no data was published anymore.
(Logging code is not shown in aboves link.)

Meanwhile i figured out, that the following parameter cause the issue:
```
opts.SetConnectTimeout(3 * time.Second)
opts.SetPingTimeout(1 * time.Second)
opts.SetKeepAlive(1 * time.Second)
opts.SetMaxReconnectInterval(3 * time.Second)
```
Without them I don't esperience the failing connection.
Are there timing dependencies for these values?

Nevertheless, I looking for code to identify a broken connection to the MQTT broker.
`mqttclient.IsConnected()` is NOT sufficient for this task.

How may I maintain a MQTT connection for a daemon?
Due to overhead, I don't want to establish a connection for each data transmission.
Is there demo code out there?

Any feedback is welcome.

**Comment by alsm** [comment]
The KeepAlive and PingTimeout settings were probably causing most of the trouble. KeepAlive is saying to the server that you will send a ping message when 1 second has passed since the last message, the mqtt spec says that the server should allow 1.5 times keepalive for a ping to arrive, unfortunately with a 1 second keepalive that's still very short and can easily be lost to timers and transmission times. Equally with the pingtimeout you're only allowing one second for the ping to get to the server, and for you to receive the servers response. Unless you really feel it is necessary I usually leave these at the default values.

With AutoReconnect enabled IsConnected() will return true unless you have called Disconnect(), the intention is that the mqtt client will handle reconnecting for you (assuming that reconnection is possible), in the mean time it will attempt to buffer any sent messages and send them once the client has been reconnected.
If this does not work for your use case you can disable auto reconnect and IsConnected() will return false unless actively connected. You can either attempt to connect again as you are currently, or use the ConnectionLostHandler to start a reconnect manually.

Typically I've found the autoreconnect functions to be sufficient to handle networking blips, and not using such aggressive timings for pingtimeout and keepalive should stop your client from triggering the disconnects itself.
Even with autoreconnect enabled the OnConnectionLost and OnConnect handlers still fire when the states change if you want to track connectivity yourself while relying on autoreconnect to handle reconnecting for you.

**Comment by Trickx** [comment]
Al S-M, thanks for the clarification.
This is very useful information. 
I'm wondering why this is not included in the official documentation.
From my point of view, it should be added.

However, in my project measurement data (actuals) is sent over MQTT without any timestamps.
For my system it does not make sense to buffer this data if the connection was lost.
The receiver would mess up timestamps, which are generated on reception of MQTT data.
So, I will rely on the autoreconnect feature but will disable publication of measurement data via `OnConnectionLost` and re-start on `OnConnect`.

Thank you!
Trickx

**Comment by alsm** [comment]
Thanks, I'll look to improve the docs and add this in.
