### ISSUE TITLE
depfile: release directory not found in tarball

### ISSUE THREAD

**Issue by andig** [eclipse/paho.mqtt.golang#189]
I'm trying to depend on paho using a `depfile`:

    github.com/eclipse/paho.mqtt.golang version=1.1.0

This fails with gobuild:

    ❯ gb build all
    fetching github.com/eclipse/paho.mqtt.golang (1.1.0)
    FATAL: unable to construct context: release directory not found in tarball

I'm new to go, hoping this is not bogus.

**Comment by nesv** [comment]
@andig gb might be trying to resolve the `1.1.0` tag, which doesn't exist. The tag is `v1.1.0`. However, after reading through gb's documentation &mdash; it's been a while since I've used gb personally, and the `depfile` thing is "new" to me (I recall it using `vendor/manifest`) &mdash; it may be a bug in gb itself.

**Comment by andig** [comment]
Thanks for this hint, will try this. Closing here in the meantime.

**Comment by nesv** [comment]
You're most welcome! :smile:
