### ISSUE TITLE
QoS=0 messages should not be delivered on AutoReconnect

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#2]
migrated from Bugzilla [#486959](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486959)
status RESOLVED severity *major* in component *MQTT-Go* for *1.2*
Reported in version *unspecified* on platform *PC*
Assigned to: Al Stockdill-Mander

On 2016-02-01 13:58:51 -0500, Mark Mindenhall wrote:

> When I create a client with SetAutoReconnect(true) in the ClientOptions, the client behaves as if the connection is never lost.  When the broker is actually disconnected, c.IsConnected() always returns true, while c.reconnect() tries to reconnect in a separate goroutine.
> 
> This means that when the client is used to Publish messages, they are written to the c.obound channel (which buffers up to 100 messages) regardless of QoS, to be delivered if/when the connection is reestablished.  However, per the spec (v3.1.1, section 4.3.1), QoS=0 behavior should be as follows:  "No response is sent by the receiver and no retry is performed by the sender."
> 
> The AutoReconnect feature is out of compliance here, because delivering these on reconnect is most definitely a "retry".  Furthermore, not dropping these messages allows QoS=0 messages to possibly prevent messages with higher QoS from being delivered.  This is because the internal c.obound channel buffer length is set to 100, which means only the most recent 100 messages will be buffered to publish on reconnect.  QoS=0 messages should never prevent QoS=1 or QoS=2 from being delivered in this way.
> 
> My current project provides a concrete example of this problem.  We publish a heartbeat message with QoS=0 at a configurable interval (e.g., every 10 seconds), and various other mission-critical messages at QoS=1.  If we lose connection to the broker, there's no value to our application in delivering the delayed heartbeat messages, and these would eventually prevent more important messages from being delivered.
> 
> Marked as "major" due to this feature being out of conformance with the spec.

On 2016-02-08 06:24:48 -0500, Al Stockdill-Mander wrote:

> This issue should be resolved by the changes in these commits
> http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.golang.git/commit/?id=SHA: 5687bf80a7457da62ca420c1854300b54e4b92d6
> http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.golang.git/commit/?id=SHA: 617c801af238c3af2d9e72c5d4a0f02edad03ce5
> 
> The second also allows you to set the size of buffers on the internal channels but only allows it when using autoreconnect. Please let me know if this change doesn't work as expected.

**Comment by mmindenhall** [comment]
Verified...thanks @alsm!

**Comment by icraggs** [comment]
Just FYI.  I realize that this issue is closed now, but I disagree that it's clear that sending QoS 0 messages under these circumstances is wrong.  I wouldn't class this as a retry.  I think we should visit this question for the other client implementations.

**Comment by mmindenhall** [comment]
Hi @icraggs, I think it makes sense to apply the [duck test](https://en.wikipedia.org/wiki/Duck_test) -- i.e., if it _looks_ like a retry, and _behaves_ like a retry, it's a retry!

We can only say this is not a **_retry_** because at the time the user publishes the message, we know we are disconnected and therefore delay the initial **_try_**.  But from the user's viewpoint of the client as a black box, the observable behavior and end result is exactly the same as a retry.

That said, I can certainly understand that there may be use cases where caching QoS 0 messages for delivery on reconnect would be preferred.  If you decide to restore the previous behavior, please ensure that:

1.  Queuing QoS 0 messages when disconnected can be disabled with a configuration option.
1.  QoS 0 messages can never prevent higher QoS messages from being delivered.  This was the case at the time I filed the bug.

**Comment by icraggs** [comment]
Well, it doesn't look like a retry to me :-)

Personally, I think it should be a configuration option, until, and if at such a time the standard makes it clear.

**Comment by icraggs** [comment]
Oh, I'm going to ask the question on the Paho mailing list, to canvas a wider audience.
