### ISSUE TITLE
Time intensive subscribe handler causes "pingresp not received, disconnecting" error

### ISSUE THREAD

**Issue by iwittkau** [eclipse/paho.mqtt.golang#208]
I have two independent components: one that publishes messages to topics and one that receives theses messages through a topic subscription.

My receiver has to do a rpc call in its handler function, which may take some time. This will eventually cause the ping error `pingresp not received, disconnecting`.

Examples to reproduce:
[pusher](https://gist.github.com/iwittkau/b67f5abcc83172e933eb281ef3f4fc67)  
[receiver](https://gist.github.com/iwittkau/5069b3ce489113850a71063d490c73db)

Observations:
- It is possible to mitigate the error by running the time intensive rpc call in a go routine.
- If the receiver also publishes messages I wasn't able to reproduced the error.

**Comment by alsm** [comment]
If message ordering is enabled message (SetOrderMatters in options.go, default true) then message handlers are called synchronously. This blocks matchAndDispatch(), which blocks alllogic() and so is unable to process a pingresp that has been sent in response to the ping. Combined with the very low ping timeout you have set for your code (I don't recommend having it this low, it will cause problems) the ping timer is hit, and the window to receive a pingresp is covered by the sleep in your handler.
The reason is doesn't happen when you are also publishing (assuming you are publishing sufficiently often) is that the client only sends a ping when it knows it hasn't sent a message to the server in x time, and resets that timer every time it sends a message. In your case that means that a ping is never required to be sent and even though you're sleeping in the handler it doesn't matter as the client is not looking for a pingresp.

**Comment by iwittkau** [comment]
Thank you @alsm for the clarification! Can you give me a recommendation for a sane ping timeout duration? Or does it depend on the general setup?

**Comment by alsm** [comment]
The default is 30 seconds, I'd be inclined to leave it at that unless you start to face any particular issues. The origin of the ping timeout is for network connections that can fail in an unclear way, for example mobile data, where there can be no tcp indication that the connection is gone but you don't want to keep sending data if it's not clear the server is receiving it.

**Comment by iwittkau** [comment]
I ran my demo code agin with the following options: 

```go
opts.SetKeepAlive(2 * time.Second)
opts.SetPingTimeout(30 * time.Second)
opts.SetOrderMatters(false)
``` 

Default ping timeout seems to be [10 seconds](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L100), btw.

Now the broker disconnects my client:
```
panic: read tcp XXX.XXX.XXX.XXX:52260->198.41.30.241:1883: read: connection reset by peer
```

I know, I can avoid this by executing my time intensive handler method in a goroutine. But is this still expected behaviour?

**Comment by alsm** [comment]
Sorry, I mixed up the terms, KeepAlive is what I meant that is default 30 seconds, and it is ping timeout that is 10. In my last reply where I said ping timeout please read keep alive. The ping timeout is how long to wait after sending a ping to wait for the ping rest, the low keep alive time is probably still causing your issues.
