### ISSUE TITLE
client stops receiving messages after 20-30

### ISSUE THREAD

**Issue by engblh** [eclipse/paho.mqtt.golang#247]
i am using same sample code provided by pahoo. I changed the qos 0 to 1 (for publish and subscribe), and instead of publishing 5, changed to 1000. Broker i am using EMQ broker. goLang client publishes 1000 message, but can not receive more than 20-30 messages. Also, i have another client, which is pahoo-python, which receives the 1000 messages, without any issue.

**Comment by engblh** [comment]
Here is code:

package main

import (
	"fmt"
	"os"

	//import the Paho Go MQTT library
	MQTT "github.com/eclipse/paho.mqtt.golang"
)

//define a function for the default message handler
var f MQTT.MessageHandler = func(client MQTT.Client, msg MQTT.Message) {
	fmt.Printf("TOPIC: %s\n", msg.Topic())
	fmt.Printf("MSG: %s\n", msg.Payload())
}

func main() {
	//create a ClientOptions struct setting the broker address, clientid, turn
	//off trace output and set the default message handler
	opts := MQTT.NewClientOptions().AddBroker("tcp://localhost:1883")
	opts.SetClientID("go-simple")
	opts.SetDefaultPublishHandler(f)

	//create and start a client using the above ClientOptions
	c := MQTT.NewClient(opts)
	if token := c.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	//subscribe to the topic /go-mqtt/sample and request messages to be delivered
	//at a maximum qos of zero, wait for the receipt to confirm the subscription
	if token := c.Subscribe("topic/sample", 1, nil); token.Wait() && token.Error() != nil {
		fmt.Println(token.Error())
		os.Exit(1)
	}

	//Publish 5 messages to /go-mqtt/sample at qos 1 and wait for the receipt
	//from the server after sending each message
	for i := 0; i < 1000; i++ {
		text := fmt.Sprintf("this is msg #%d!", i)
		c.Publish("topic/sample", 1, false, text)
		//token.Wait()
	}

	//time.Sleep(3 * time.Second)

	//unsubscribe from /go-mqtt/sample
	// if token := c.Unsubscribe("topic/sample"); token.Wait() && token.Error() != nil {
	// 	fmt.Println(token.Error())
	// 	os.Exit(1)
	// }

	//c.Disconnect(250)

	select {}
}

**Comment by alsm** [comment]
Thanks for reporting that, I forgot to ensure, with accepting a PR that allows the user to ack the message to indicate it has been processed, that the message was acked after the handler returned

**Comment by xeizmendi** [comment]
The reason behind letting the user Ack is to pass the control to the user.
The message handler might return (because blocking in the message handler is not a good idea) but you might still be processing this message. When a user selects QoS 1 or 2 they should ensure they ack the message once processed, even if it's not processed by the message handler itself.
I'll give an example, pass a channel to a message handler so the messages get processed in another goroutine. The message handler will return, but you don't want it to ack until you know you have actually processed the message.

Your commit defeats the whole purpose of deferring the ack to the user...

**Comment by alsm** [comment]
Without that change I've just broken all current users of the library because their code does not Ack the message, that is not acceptable.
The mechanisms now exist that changes could be made to allow the user of the library to opt in to taking over control for acking messages, this is not high on my priority list but I'd happily take PRs if someone wishes to implement it.
