### ISSUE TITLE
Messages in file store sent out of order if store contains more than 10 messages

### ISSUE THREAD

**Issue by FabianInostroza** [eclipse/paho.mqtt.golang#251]
The list of files in the store is sorted alphabetically so o.10.msg is read before o.2.msg and so on

**Comment by alsm** [comment]
There is no guarantee that lower numbered msgs in the store were sent before higher numbers, when a msgid is requested the first unused number in the map is used, as these numbers are released they made available again.

**Comment by FabianInostroza** [comment]
From the documentation [1]:
> SetOrderMatters will set the message routing to guarantee order within each QoS level. By default, this value is true. If set to false, this flag indicates that messages can be delivered asynchronously from the client to the application and possibly arrive out of order. 

Isn't this behavior in conflict with what one would expect if I use `SetOrderMatters(true)` (default option) and send messages with QoS 2?.

[1]: https://godoc.org/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetOrderMatters

**Comment by alsm** [comment]
I understand where you're coming from, I think the documentation could be more explicit that this ordering is about the passing of messages received by the library to the application, it basically single threads the router so that each message handler is run synchronously and waited to return before calling the next or processing the next message.
There is no guaranteed ordering on the sending side, beyond doing a publish and waiting for the token to complete to know it was received by the server.

Thinking about this though it should be possible to sort them by modified time and use that order to republish.
