### ISSUE TITLE
A Single Client Subscribes to a Topic with Multiple callbacks

### ISSUE THREAD

**Issue by jjm011** [eclipse/paho.mqtt.golang#268]
Hi,

I am trying to provide a wrapper of the mqtt client library in my system, so different services can use the same client. My only concern is how to manage the different services to receive multiple copies of the same client subscribing to a same topic.
ex: serviceA wants to subscribe to topic /data with callback function ServiceACallback, serviceB wants to subscribe to topic/data as well but on callback function ServiceBCallback, but I am only using one client to make the connection for my entire system.

Is there a way to do this from the library? Or I have to create a mapping for each of the callback functions and make copies on my own?

Any suggestion for my current design is deeply appreciated!

**Comment by MattBrittan** [comment]
Apologies for the lack of response on your issue. For reference the design of the router does not appear to support your use case (if a second route is added for one topic then the first one is overwritten); this is inline with the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc384800440) "If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription".

Closing this issue due to its age.

**Comment by aldas** [comment]
@MattBrittan It would be really useful if https://github.com/eclipse/paho.mqtt.golang/blob/a1800d8df9a4278dd3789f466fa15fafbe1dbd9f/router.go#L100 would warn user when existing subscription is overwritten.

I have a similar situation where I have multiple services subscribing to same topic in same application and spend quite some time to investigate why only one of them receives messages.

Warning would be nice if there are no logic to allow multiple handlers observing/listening on the same topic (client side propagate messages to all observers, not server-side).

**Comment by MattBrittan** [comment]
@aldas - I guess it might be worth adding a comment to [`AddRoute`](https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L113)'. It would also be possible to log a warning when an existing route is overwritten (that's really the only way of alerting the user without a breaking change). 
Changing the behaviour of the router itself would be a breaking change likely to result in callbacks being called multiple times so probably not an option currently.
