### ISSUE TITLE
occasional deadlock when connections are lost

### ISSUE THREAD

**Issue by foxxnuaa** [eclipse/paho.mqtt.golang#328]
Hi,all:
i also met this problem yet.
when the network is not stable,i can see the log bellow:
pingresp not received, disconnecting
error triggered, stopping
internalConnLost
incoming dropped a received message during shutdown
outgoing stopped
incoming stopped

then no connections left and will not reconnect again.

the goroutine alllogic was not received the stop signal.so the internalConnectionLost waits forever for c.workers.Wait() to return

this is in small chance.
but will lead to problem.
can you help solve this problem in new version?

**Comment by kamermans** [comment]
Interesting - this certainly looks related, thanks!

**Comment by MattBrittan** [comment]
Are you still experiencing this issue? (there have been some changes in the package since this was raised). I think there is still a potential issue with the error channel (the routine that reads it exits as soon as an error is received but there are a few situations where multiple errors might be sent leading to a deadlock).

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
