### ISSUE TITLE
a issue for Client

### ISSUE THREAD

**Issue by L-jasmine** [eclipse/paho.mqtt.golang#340]
https://github.com/eclipse/paho.mqtt.golang/blob/93c8a06e1e6dfeb17dd18a44e3e2f4e1db778237/client.go#L141

if new a Router in NewClient(). when I call client.Connect() after client.Disconnect(),router is close and no a new router is working.
Can new a Router in Connect()? link:

```
func (c *client) Connect() Token {
	var err error
	t := newToken(packets.Connect).(*ConnectToken)
	DEBUG.Println(CLI, "Connect()")

*	c.msgRouter, c.stopRouter = newRouter()
*	c.msgRouter.setDefaultHandler(c.options.DefaultPublishHandler)

	c.obound = make(chan *PacketAndToken, c.options.MessageChannelDepth)
	c.oboundP = make(chan *PacketAndToken, c.options.MessageChannelDepth)
	c.ibound = make(chan packets.ControlPacket)
```

**Comment by MattBrittan** [comment]
As you mentioned creating a NewClient will create a new router. The router is a private and there is currently no way for you to access this directly (by design).

For a new connection you have two options:
* opts.SetDefaultPublishHandler -  Sets the MessageHandler that will be called when a message
 is received that does not match any known subscriptions. You can then handle these however you wish.
* client.AddRoute  - allows you to add a handler for messages on a specific topic without making a subscription

Note: I'd suggest using opts.SetOnConnectHandler to setup a function that will be called when a connection is completed. In that function you can call Subscribe to subscribe to any topics you are interested in (calling this on every connection should not be an issue and will ensure that you are subscribed to the relevant topics).

**Comment by L-jasmine** [comment]
> As you mentioned creating a NewClient will create a new router. The router is a private and there is currently no way for you to access this directly (by design).
> For a new connection you have two options:
> 
> opts.SetDefaultPublishHandler -  Sets the MessageHandler that will be called when a message
> is received that does not match any known subscriptions. You can then handle these however you wish.
> client.AddRoute  - allows you to add a handler for messages on a specific topic without making a subscription
> 
> Note: I'd suggest using opts.SetOnConnectHandler to setup a function that will be called when a connection is completed. In that function you can call Subscribe to subscribe to any topics you are interested in (calling this on every connection should not be an issue and will ensure that you are subscribed to the relevant topics).

Router will stop when I call client.Disconnect(),
Because router is not working, opts.SetDefaultPublishHandler And client.AddRoute is useless.

**Comment by MattBrittan** [comment]
Sorry - I misunderstood your point. If I'm understanding you correctly you are:
 - Creating a client (NewClient())
 - Connecting
 - Disconnecting
 - Attempting to connect again using the same client

You are correct in that this will not work. I believe that your proposed solution would break other uses (e.g. Calling NewClient, using client.AddRoute to add routes and then calling connect).

The solution for your issue will depend upon your requirements. You could use the AutoReconnect option if you are trying to deal with network issues or create a new client if you just want to manually disconnect/reconnect. I'm sure it would be possible to change client.go to allow Connect() to be called again; your best bet would be to submit a pull request for that (as mentioned it would be a bit more complex than your suggestion to avoid breaking existing code; I'd also suggest explaining why the modification is needed e.g. why you cannot call NewClient() ).

**Comment by alsm** [comment]
If you want consistent behaviour like this you could do your AddRoute calls in the OnConnectHandler

**Comment by ackratos** [comment]
> You are correct in that this will not work. I believe that your proposed solution would break other uses (e.g. Calling NewClient, using client.AddRoute to add routes and then calling connect).


If that's the only case, I guess if I forked this repo and my client code doesn't call AddRoute then the reconnect logic will be fine with original proposed "fix" isn't it?

```
func (c *client) Connect() Token {
	var err error
	t := newToken(packets.Connect).(*ConnectToken)
	DEBUG.Println(CLI, "Connect()")

*	c.msgRouter, c.stopRouter = newRouter()
*	c.msgRouter.setDefaultHandler(c.options.DefaultPublishHandler)

	c.obound = make(chan *PacketAndToken, c.options.MessageChannelDepth)
	c.oboundP = make(chan *PacketAndToken, c.options.MessageChannelDepth)
	c.ibound = make(chan packets.ControlPacket)
```

**Comment by ackratos** [comment]
> If you want consistent behaviour like this you could do your AddRoute calls in the OnConnectHandler

this won't work as client.router's stop channel has been closed, without assign a new router instance, this select will always directly quit:

```
func (r *router) matchAndDispatch(messages <-chan *packets.PublishPacket, order bool, client *client) {
	go func() {
		for {
			select {
			case message := <-messages:
                         .......
                         .......
			case <-r.stop:
				return
```

**Comment by MattBrittan** [comment]
> If that's the only case, I guess if I forked this repo and my client code doesn't call AddRoute  then the reconnect logic will be fine with original proposed "fix" isn't it?

The same applies to ```Subscribe``` (internally this calls ```c.msgRouter.addRoute```) but as long as you reestablish all routes (remember that the broker will remember subscriptions if ```CleanSession``` is ```false```) I think that would work (obviously you can implement whatever functionality you like in a fork). My comment was in regards to making this change to [github.com/eclipse/paho.mqtt.golang](https://github.com/eclipse/paho.mqtt.golang); I feel it would be a breaking change (it would break my code) so providing a rationale for the change would help assess if it is worthwhile (hence my suggestion to @L-jasmine that they explain why they feel this change is valuable i.e. what are the benefits over just calling ```NewClient``` or use the existing ```AutoReconnect``` feature).

>If you want consistent behaviour like this you could do your AddRoute calls in the OnConnectHandler

I think the comment from @alsm may have been in response to my comment re calling ```AddRoute``` before ```Connect()```. I take this approach because when running with ```CleanSession``` set to```false``` (particularly with QOS 1/2) you can receive messages immediately after connecting (before calling ```Subscribe```) and this means you need to either manually add a route or handle the messages in ```DefaultPublishHandler```. While it is possible to call ```AddRoute``` from the ```OnConnectHandler``` this is started as a goroutine within ```Connect()``` meaning there is still a chance that messages will arrive before the route is added (this is unlikely but I believe its possible; the broker can send messages immediatly after the ```CONNACK ``` and the order goroutines are scheduled is not defined so my approach seemed safer).

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
