### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by caevv** [eclipse/paho.mqtt.golang#343]
Some important fixes, would you create a new release?
Thanks

**Comment by magallardo** [comment]
Is there going to be a new release?

**Comment by YiuTerran** [comment]
Hope for new release and closing resolved issue...

**Comment by JohnRoesler** [comment]
Could we get a release? I have had a few bugs occur with the latest release and pointing directly to master has resolved them.

**Comment by MattBrittan** [comment]
I have just released version 1.3.0. There have been no changes (other than documentation) since mid September, a lot of users are following `@master`, and no actionable issues have been raised so I believe sufficient testing has been undertaken . However as the last release (v1.2.0 - April 2019) was some time ago this release does include significant changes; I don't believe any of them are breaking. 

Note that there was [one commit](https://github.com/eclipse/paho.mqtt.golang/commit/782a0f6f87cc9dedb511cbfa8ea6f064590d7836) that I believe could impact some users; this changed the message channels used internally from buffered to unbuffered. This have an impact where messages are being published from within handlers (any potentially blocking operation within a handler may cause issues and should be avoided).

**Comment by MattBrittan** [comment]
Closing this because `v1.3.0` is out and there have been no new related issues raised.
