### ISSUE TITLE
[Question] how to use crt file and  key file for ssl

### ISSUE THREAD

**Issue by liangyuanpeng** [eclipse/paho.mqtt.golang#348]
my code

```
// Import trusted certificates from CAfile.pem.
	// Alternatively, manually add CA certificates to
	// default openssl CA bundle.
	certpool := x509.NewCertPool()
	pemCerts, err := ioutil.ReadFile("/client/ca.crt")
	if err == nil {
		certpool.AppendCertsFromPEM(pemCerts)
	}

	// Import client certificate/key pair
	cert, err := tls.LoadX509KeyPair("/client/client.crt", "/client/client.key")
	if err != nil {
		panic(err)
	}
```

i juse change ``pem``  to ``key`` and ``crt`` 
but i got some error 
```
panic: tls: failed to find "CERTIFICATE" PEM block in certificate input after skipping PEM blocks of the following types: [TRUSTED CERTIFICATE]
```

i try to run command from server and it working

```
mosquitto_sub -p 8883 -t MqttTest --cafile ca.crt --cert client.crt --key client.key

mosquitto_pub -p 8883 -t  MqttTest -m "status" --cafile ca.crt --cert client.crt --key client.key
```

**Comment by MattBrittan** [comment]
Hi @liangyuanpeng, Your code looks fine to me so I'd say that the issue is due to something in your certificate. Different libraries take different approaches when parsing certificates and sometimes the go standard library will reject a certificate that another library might accept.

The error are getting indicates that when scanning the certificate the code did not find:

`-----BEGIN CERTIFICATE-----` 
Optional Headers 
 base64-encoded Bytes 
`-----END CERTIFICATE-----` 

I would suggest clearing out everything except the certificate (so just the BEGIN line through to the END line) from your file and trying again. 

Unfortunately its not really possible to assist further without seeing the certificate you are trying to load (but as this is really a general go question I'd suggest asking on a site like stackoverflow because you will get faster/better answers). Also please note that the code that parses the certificate is written in Go so stepping through it in the debugger could help you identify where things are going wrong.

Matt

**Comment by baorongquan** [comment]
@liangyuanpeng   I have same problem. Did you reslove it?
