### ISSUE TITLE
go get and documentation discrepancy

### ISSUE THREAD

**Issue by FantasticFiasco** [eclipse/paho.mqtt.golang#349]
I'm new to Go and apologize upfront if my question is stupid, or if the answer is something I ought to know before writing any Go code.

I use vgo and wanted to try your code, especially the proxy support when using websockets that you mention in your `README.md`. But when I did a `go get github.com/eclipse/paho.mqtt.golang` I didn't get the proxy support, but instead got the latest `v1.2.0` release. I guess that is how `go get` works? Should I specify your latest git commit sha during `go get` or is there a better way to get the latest features of your package?

**Comment by MattBrittan** [comment]
Hi @FantasticFiasco, I'd suggest using `go get github.com/eclipse/paho.mqtt.golang@master` as that will give you the latest version without requiring you to lookup commit sha's (but its best to use this only when you need a feature that is not in the lastest released version because releases are better tested than master). 

You are right that the `readme.md` is a little confusing on this; however:
-  there is an open issue requesting a new release
- until go 1.14 is released not everyone will be using go modules by default (if go modules are not in use then `go get github.com/eclipse/paho.mqtt.golang` will get the master by default). 

Matt

PS. You will probably get a better/faster answer posting this kind of question somewhere like Stack overflow.

**Comment by FantasticFiasco** [comment]
Thank very much for you answer! Didn't know about `@master` nor the behavior when not using vgo.
