### ISSUE TITLE
[Question] subtopic restricted?

### ISSUE THREAD

**Issue by bluecodefish** [eclipse/paho.mqtt.golang#350]
Is the topic restricted to only 2 levels?
If i want to subscribe to topic   "aaaaa/bbbbbb/cccc/ddd/eee/#" the client receives all messages from "aaaaa/bbbbbb/cccc"...

**Comment by MattBrittan** [comment]
> Is the topic restricted to only 2 levels?
The library should work fine for deeper subscriptions (in fact if you are only subscribing to "aaaaa/bbbbbb/cccc/ddd/eee/#" then your broker should not be sending you anything else).

> ...the client receives all messages from "aaaaa/bbbbbb/cccc"...
Please post some sample code demonstrating the issue.

Matt

**Comment by bluecodefish** [comment]
Hi Matt, 
i'm using the sample code:


	`
		choke := make(chan [2]string)

		opts.SetDefaultPublishHandler(func(client MQTT.Client, msg MQTT.Message) {
			choke <- [2]string{msg.Topic(), string(msg.Payload())}
		})

		client := MQTT.NewClient(opts)
		if token := client.Connect(); token.Wait() && token.Error() != nil {
			panic(token.Error())
		}

		if token := client.Subscribe(topic, 0, nil); token.Wait() && token.Error() != nil {
			fmt.Println(token.Error())
			os.Exit(1)
		}

		for {
			incoming := <-choke
			var message Message
			json.Unmarshal([]byte(incoming[1]), &message)
                        ...
                        ...
			}`

where topic is defined as: 

channels/f672bf0c-4a12-4af5-a906-c584baf71fba/messages/dev/some/sub/channel

I'm receiving though all messages from "channels/f672bf0c-4a12-4af5-a906-c584baf71fba/messages/"

if i change the topic to ".../messages/what/ever" it has no effect at all, i'm still receiving all messages from all subchannels

**Comment by MattBrittan** [comment]
You are using `opts.SetDefaultPublishHandler` which "sets the MessageHandler that will be called when a message is received that does not match any known subscriptions.". In addition you are not registering a handler when subscribing (the third paramater to Subscribe) meaning that no specific message handlers are registered.

The upshot of this is that the handler you pass to SetDefaultPublishHandler will receive ALL messages received from the broker (regardelss of topic). So your question probably should be "Why is the broker sending me information on topics that I have not subscribed to?".

If you want this package to filter the messages received and only pass them onto your application if you have subscribed to them then pass a handler into the Subscribe function (the third argument); that handler will only be called when a message on the specified topic is received. Note that if receiving every message is important to you (and I assume it is not as you are using QOS 0) you may want to use `AddRoute` too because subscribe can only be called after you have connected and, for reasons desciribed below, messages can arrive between the time the connection comes up and the subscribe call is processed.

**Bonus answer** to "Why is the broker sending me information on topics that I have not subscribed to?". 

This is subject to the specific broker you are using, not directly related to this package, and dependent upon information you have not supplied (e.g. the cleansession option setting). So the following is a guess.... 

The mqtt spec states that upon connection `If CleanSession is set to 0, the Server MUST resume communications with the Client based on state from the current Session (as identified by the Client identifier)`. The sesion state includes, amongst other things, the Client’s subscriptions. 

This means that if you connect to a broker as a particular client ID, subscribe to some topics, disconnect and then reconnect (with the same client ID and cleansession set to 0) then your new connection will be subscribed to those topics and will receive any new messages (if QOS=1 or 2 then you will also receive any messages received by the broker whilst your connection was down).

So my guess is that you have CleanSession set to false (the default is true) and have previouslly subscribed to other topics (e.g. #) using the same client identifier.

Note that this behaviour is dependent upon the broker and its configuration (for example mosquitto will loose session information when it is restarted unless `persistence true` is in the config).

**Comment by bluecodefish** [comment]
Hi Matt,
thanks a lot for the very informative answers. I completely reorganized my code and now it's working fine.
