### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by drasko** [eclipse/paho.mqtt.golang#368]
Hello Paho maintainers,
this project seems important for a comunity, but I am surprised with inactivity.

Latest commit was done 2 months ago, and there are 7 outstanding PRs at this moment with practically no comments at all and moreimportantly no reviews or instructions from maintainers.

What should be the problem?

**Comment by alsm** [comment]
Hi, it is still active (although I've put more effort into the new MQTTv5 library https://github.com/eclipse/paho.golang recently), partly the issue is that I am the only maintainer (although I am grateful the involvement of @MattBrittan recently) and have to find time to dedicate to looking at issues/PRs properly, and particularly that there seems to have been a fair bit of activity in the last 2 weeks while I've been away on holiday.
I am grateful to anyone who takes the time to report issues and do PRs, and if we're getting to a point where there is more involvement and activity than I can handle alone I'm happy to look at how we can address that.

The code base here though started several years ago, and decisions were made that can not be unmade but make it harder to extend properly. That's one reason I'm less keen on adding new features to this client, ideally I would like to make it maintenance only and add MQTTv3.1.1 functionality to the v5 codebase which I think is designed and written in a better more maintainable style.

I'll endeavour to be more responsive to issues and PRs though.

**Comment by drasko** [comment]
@alsm thanks for the sresponse.

Does this new https://github.com/eclipse/paho.golang  support MQTTv3.1 as well, or is it MQTTv5-only?

If it does support both, then it probably makes sense to switch to this new code-base and starts using it, at least to test it and discover some bugs.

**Comment by alsm** [comment]
Unfortunately not, right now it's v5 only as it's proving out the new design, and I haven't worked out how best to support 3.1.1 there (new client in same style or extend v5 to do 3.1.1). I'd be grateful to anyone who has the time to look at that client and give some feedback. Maybe I should do a doc explaining the design and ideas behind it.On 23 Oct 2019 19:08, Drasko DRASKOVIC <notifications@github.com> wrote:@alsm thanks for the sresponse.
Does this new https://github.com/eclipse/paho.golang  support MQTTv3.1 as well, or is it MQTTv5-only?
If it does support both, then it probably makes sense to switch to this new code-base and starts using it, at least to test it and discover some bugs.

**Comment by drasko** [comment]
@alsm thanks for the info, I'll close this issue.

Just to let you know - yesterday's merge provoked regression: https://github.com/eclipse/paho.mqtt.golang/issues/370

It would be great if you can take a look at this so we can have working master.
