### ISSUE TITLE
Redundant cases in net.go

### ISSUE THREAD

**Issue by huornlmj** [eclipse/paho.mqtt.golang#369]
Case 1 on line 252 (c.incomingPubChan <- m) is identical to case 2 on line 249.  Why is this?

**Comment by MattBrittan** [comment]
Because we want to take the same action when QOS is 1 or 2. It would be possible to use fallthrough to remove the duplication (or change this to an if) but as it's only a couple of lines I'm not sure that it's a big deal?

Having said that this is an area I've been looking at as I feel that the QOS0 approach should probably be taken in all cases (or larger changes made). The incomingPubChan was previously a buffered channel if AutoReconnect was on; this was changed in a recent PR and I suspect that may lead to a potential deadlock where alllogic is sitting at ```c.incomingPubChan <- m``` but matchAndDispatch has already terminated so nothing is listening on c.incomingPubChan.

**Comment by alsm** [comment]
Yeah, I think it's an artifact from (way back) when there was more specific code for each case, the client used to automatically send the appropriate ack for each qos type as soon as it had received the message rather than after the handler had returned. When this was changed the code was taken out but the cases weren't collapsed/simplified as they should.
