### ISSUE TITLE
Unsubscribe get stuck

### ISSUE THREAD

**Issue by dusanb94** [eclipse/paho.mqtt.golang#370]
Unsubscribe token.Wait() waits indefinitely, even if Unsubscribe Ack is received. This was not happening before [PR 361](https://github.com/eclipse/paho.mqtt.golang/pull/361). Looks like the problem is related to the code removed from `net.go`. You can use the following snippet to get stuck:
```go
	mc := mqtt.NewClient(opts)
	token := mc.Connect()
	token.Wait()
	if err := token.Error(); err != nil {
		fmt.Printf(err)
		return
	}
	mc.Subscribe(topic, 2, handler)
	// Wait for SUB ACK.
	time.Sleep(3 * time.Second)
	if mc.Unsubscribe(topic).Wait() {
		fmt.Println("done")
	}
        // Never reached. Network inspection shows Unsubscribe ACK received.
	fmt.Println("never reached")
```

**Comment by alsm** [comment]
Thanks for reporting this, I didn't notice that the changes that were made for subscribe hadn't been made for unsubscribe and it didn't break the tests (unfortunately)

**Comment by robbawebba** [comment]
@dusanb94 I apologize for breaking the behavior of your application (and probably others), and thank you @alsm for fixing the issue! I totally forgot about the unsubscribe flow because my application does not use the unsubscribe features of this client, and I just relied on the library's test suite for verifying that I did not break any existing functionality.
