### ISSUE TITLE
Publish message to a specific client ID

### ISSUE THREAD

**Issue by bcashier** [eclipse/paho.mqtt.golang#378]
Hi,

Is it possible to publish message to a specific client id ?

I want to publish two things using mqtt:
1- General informations like users scores, stats etc ... and can be viewable by everyone.
2- Sensitive informations reserved for private user like own score, name etc ...

Is there any clean way to do it using Paho MQTT ?

Thank you

**Comment by MattBrittan** [comment]
Hi @bcashier, 
I answered one of your [previous questions](https://github.com/eclipse/paho.mqtt.golang/issues/357) that was on [stack overflow](https://stackoverflow.com/questions/58175550/what-is-the-right-way-to-use-this-code-paho-mqtt-as-goroutine-and-pass-message) and this one is also identical to a [post on stack overflow](https://stackoverflow.com/questions/58597403/publish-message-to-a-specific-client-id) from a different user. Posting questions in both places (or worse cross-posting other peoples questions) wastes time; particularly when the question was only raised on Stack overflow today.

This question is a general 'how to use MQTT' type question so stack overflow is a more appropriate forumn (so I'll respond there).

**Comment by bcashier** [comment]
@MattBrittan Thank you for your answer.

But unfortunatelly is not a general "How to use MQTT" ... I need to provide sensitive informations to a specific Client ID / User using for example a token generated when logged in.

Publishing messages to a general topics is already done and it's not what I want right now.

Thanks again.

**Comment by MattBrittan** [comment]
Sorry @bcashier by "How to use MQTT" I mean that the question is about MQTT protocol in general rather than something specific to the paho libraries (which implement the MQTT protocol). Please see the response to the question on stack overflow (it was answered when I was part way through typing in the same basic answer). 

"I tought about creating a specific topic for each logged in user but it will consume many of in memory usage" - As per the stack overflow answer creating a seperate topic per logged in user is the only real approach to this under the MQTT protocol. It will consume some resources on the broker but that is really unavoiadable. 

However you do this the messages are going to need to be tagged with a userid of some kind and the broker is going to need to know who to direct them to; using the topic for this is no worse than any other approach from a resource standpoint. The thing you will need to carefully consider is what happens when the client is offline (a broker should persist QOS1+ messages so if you are sending frequent private updates and the client goes offline permanently you need a way to stop these as otherwise you will have a resource issue).

**Comment by bcashier** [comment]
@MattBrittan 

I appreciate your answer.

I am thinking about using UserID included in topic name, by I am facing 2 problems:
1- Like you said, finding a way to stop sending messages when the user is offline.
2- Second point, is a way to add permissions automatically for each user registration (To restrict access to a topic and allow it for a specific user only)

For the first issue, is there a way to not retain the messages and discard them if no subscriber in a specific topic ? Since when the web page is reloaded, the user score is fetched from database ... only new changes will be sent and update them into the browser when the page is not refreshed ... but when the browser is closed, all messages can be discarded. Do you have any solution for this ? Do using QOS=1 will solve the problem ? Or is there any specific configuration that must be applied for this case ?

For the second point, you can to not responding ... it is just if you have already experienced it in the past or share your knowledge about it.

Many thanks again for your intervention.

**Comment by MattBrittan** [comment]
As mentioned earlier these are questions about the MQTT protocol and MQTT brokers. This repository is for an MQTT client and is not the appropriate place for this discussion.

Please close off this issue and ask your question elsewhere. I would suggest Stack overflow (where you have already asked the same question and received a number of responses) or a rabbitmq forum (based upon what you have said on Stackoverflow the answer will be specific to rabitmq because there is no real standard for MQTT broker configurations; for instance RabbitMQ is very different from Mosquitto).

**Comment by bcashier** [comment]
@MattBrittan Thanks again sir, and sorry for wasting your time :)
