### ISSUE TITLE
Support custom ACK function, check handler function status

### ISSUE THREAD

**Issue by mtojek** [eclipse/paho.mqtt.golang#396]
Hi,

the current implementation of the `paho.mqtt.golang` acknowledges incoming messages once they're received, just after calling handler function.
If the handler execution fails, the message shouldn't be acknowledged but repeated. 

I wish to see two features:
1. Pass/define a custom `Ack()` function - could be a wrapper, a decorator pattern, etc.
2. Call the `Ack()` method if only the handler function returns non-error result.

Best,
Marcin

**Comment by tonygunter** [comment]
I consume my messages then pass them off on a channel to my workers as mqtt.Message, which implements Ack().  However, the code inside router.go executes Ack() which wraps a sync.once.Do function.  So exposing Ack() this way literally does nothing because it's already been executed inside router.go inside the matchAndDispatch function.

**Comment by bconway** [comment]
IMO having the option to manually ACK a message is important for failure handling in a distributed system.

Additionally, this functionality already exists in the Java client (https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/IMqttAsyncClient.java#L823), so this is not new ground for Paho MQTT.
