### ISSUE TITLE
LastWill configuration is creating issue

### ISSUE THREAD

**Issue by hegdemahendra** [eclipse/paho.mqtt.golang#402]
Hello Team,

 

I have used this golang library to consume messages from VerneMQ broker.

Everything works fine untill I configure LastWill (like below).

 

----------

opts.SetWill(props["mqtt.apollo.dataflow.consumer.lastwill.topic"], common_utils.GetLastWillMessage(props), 2, false)

---------

 

Once I add last will, consumer fails in below scenario -
Steps :

1. Start the new go lang consumer and publish message to topic -

    Expected : consumer starts consuming - Working as expected

2. Stop the consumer and keep publishing the messages when consumer is offline and start the consumer again.

    Expected : Consumer consumes all messages which were published when it was offline - Working as expected

3. Continue publishing the messages to the topic

    Expected : Consumer should keep consuming new messages (exactly once as QOS is set to 2)

******* But here consumer is consuming messages multiple times (duplicates), duplicates happening to only those messages which are published post restart of the consumer ******
 
Thanks
Mahendra

**Comment by MattBrittan** [comment]
Hi Mahendra,

The only impact of calling ```opts.SetWill``` should be to pass the will to the broker when a connection is established; I have checked the code and this appears to be what it is doing. Because of this I suspect that the issue is most likely at the broker end (on the basis that it implements the will) but I may be wrong (are you using this solution with other clients?).

In any event to allow further investigation can you please:
 * Confirm what version of the package you are using. Ideally grab the latest code (if using modules please run ```go get github.com/eclipse/paho.mqtt.golang@master```) as there have been a number of changes since the last release.

* Check if your connection to the broker is stable (if the connection is going up and down then there are some situations where you may receive the same message multiple times; note that the duplicate flag should be set).

* Provide client logs - to enable logging use something like:
```
mqtt.ERROR = log.New(os.Stdout, "[ERROR] ", 0)
mqtt.CRITICAL= log.New(os.Stdout, "[CRIT] ", 0)
mqtt.WARN = log.New(os.Stdout, "[WARN]  ", 0)
mqtt.DEBUG = log.New(os.Stdout, "[DEBUG] ", 0)
```

* Any broker logs may also be of use.

Thanks,
Matt

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
