### ISSUE TITLE
clientID affects the connection 

### ISSUE THREAD

**Issue by Kowiste** [eclipse/paho.mqtt.golang#426]
i have a system that when i configure it with a clientID 00-00-00-00-00-00, i have the error mqtt client is not connect if I set 00-00-00-00-00-02 that doesn't happen, right now instead of pass this MAC style address I generate a UUID and works perfectly.
There is any limitation in the clientID value?

`//PublishKeepAlive : PublishKeepAlive
func (p *MQTT) PublishKeepAlive(topic string, payload string) {
	t := fmt.Sprintf(topic, p.PartnerID, p.ClientID)
	log.Printf("KeepAlive: publishing to topic %s : %s", t, payload)
	go p.client.Publish(t, 0, true, payload)
	if !p.client.IsConnectionOpen() {
		log.Printf("Error mqtt client is not connected")
	}
}`
`func (p *MQTT) createClientOptions(clientID string, uri *url.URL) *paho.ClientOptions {
	opts := paho.NewClientOptions()
	opts.AddBroker(fmt.Sprintf("%s://%s", uri.Scheme, uri.Host))
	opts.SetUsername(uri.User.Username())
	password, _ := uri.User.Password()
	opts.SetPassword(password)
	opts.SetKeepAlive(2* time.Minute)
	opts.SetClientID(clientID)
	opts.SetConnectRetry(true)
	opts.SetConnectRetryInterval(500 * time.Millisecond)
	return opts
}`

**Comment by MattBrittan** [comment]
Hi @Kowiste, 
The client id is passed to the MQTT broker as-is (this package does not impose any restrictions) so I would suggest checking your brokers logs (your issue did not provide enough detail to say much further). 

One of the most common reasons I see for loss of connection is when you have two systems connecting to a broker with the same ID (the spec mandates that when a client connects the broker must disconnect any existing connections with the same client id).

Please do note that the [MQTT spec](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349242) does not mandate that clients/brokers accept client id's with "-" in them (they can but do not have to; I doubt this is your issue but it might be worth bearing in mind).

If, after checking the brokers logs, you still believe this is an issue with this package then please enable debug logging (instructions in response to [this issue](https://github.com/eclipse/paho.mqtt.golang/issues/409)) and post the logs (and, ideally, the broker logs).

Matt 

PS. Please format any code you add to an issue; it's very hard to read otherwise. I have formatted your code and pasted it below but it does not seem to contain anything that would help diagnose the issue you reported (there are a number of reasons that the connection to the broker could be down).

```
//PublishKeepAlive : PublishKeepAlive
func (p *MQTT) PublishKeepAlive(topic string, payload string) {
	t := fmt.Sprintf(topic, p.PartnerID, p.ClientID)
	log.Printf("KeepAlive: publishing to topic %s : %s", t, payload)
	go p.client.Publish(t, 0, true, payload)
	if !p.client.IsConnectionOpen() {
		log.Printf("Error mqtt client is not connected")
	}
}

func (p *MQTT) createClientOptions(clientID string, uri *url.URL) *paho.ClientOptions {
	opts := paho.NewClientOptions()
	opts.AddBroker(fmt.Sprintf("%s://%s", uri.Scheme, uri.Host))
	opts.SetUsername(uri.User.Username())
	password, _ := uri.User.Password()
	opts.SetPassword(password)
	opts.SetKeepAlive(2 * time.Minute)
	opts.SetClientID(clientID)
	opts.SetConnectRetry(true)
	opts.SetConnectRetryInterval(500 * time.Millisecond)
	return opts
}
```

**Comment by Kowiste** [comment]
Thanks, yes it as that the same clientID in 2 program when i was testing.
