### ISSUE TITLE
TLS Session resumption 

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.golang#439]
Hi Guys,

I read something about session resumption so the client just do one TLS handshake and if it loses the connection, it will do it not again because of the session id or session tickets: https://www.hivemq.com/blog/mqtt-security-fundamentals-tls-ssl/

Is that implemented in paho.mqtt.go ? 
Or does the library just does a new handshake for every Publish/Subscribe of a client?

T

PS: I hope the github is the right place for this question, but it is specific for your implementation.

**Comment by MattBrittan** [comment]
Use ```SetTLSConfig(t *tls.Config)``` to control this (the package just uses the standard ```crypto/tls``` library). If you need further details you would be best asking elsewhere (e.g. stackoverflow) because its more of a TLS question than an paho.mqtt.golang issue. 

You control when the client connects/disconnects through ```Connect()``` and ```Disconnect(quiesce uint)``` (obviouslly there are cases where the connection may drop for other reasons and the reconnect logic may kick in if enabled). Generally you would keep a single MQTT session running as long as you need to communicate (often as long as your application is running) so in most cases the extra overhead of a handshake is not much of an issue because its a rare event.

>PS: I hope the github is the right place for this question, but it is specific for your implementation.

This is at the boundary; and might be better asked on ```StackOverflow``` because its a question rather than an issue (or potential issue). Currently there are only a few people responding to issues here so you will probably get a better response there and my preference is to keep this area for issues (time spent responding to questions means less time spent resolving issues and means issues can get lost in the noise).

**Comment by Tockra** [comment]
Okay thank you for your answere. But I think stackoverflow wouldn't be a good place. 
The question isn't how crypto/tls works. I'm sure it has options for using persistence. The question is how this mqtt solution uses this library. 
So I don't know some people from stackoverflow could help me.

**Comment by MattBrittan** [comment]
> The question is how this mqtt solution uses this library.

Unless you are using websockets or a proxy server it comes down to [one line](https://github.com/eclipse/paho.mqtt.golang/blob/master/netconn.go#L67):

```
conn, err := tls.DialWithDialer(&net.Dialer{Timeout: timeout}, "tcp", uri.Host, tlsc)
```

where ```tlsc``` is whatever you passed in using ```Use SetTLSConfig(t *tls.Config)```. So if you want to session resumption then I believe you need to set the ```tlsConfig.ClientSessionCache``` on the ```tls.Config``` you pass in (but its not something I have any experience with and is not specific to the paho package).
