### ISSUE TITLE
SSL-Connection - Certification problems

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.golang#440]
Hi Guys,

I already googled for a while and found no solution for my problem.
There is the possibility that it's a implementation problem of paho.mqtt:

I startet a local mosquitto broker with a self signed certificate (CN: 127.0.0.1). Following command works:
```bash
mosquitto_pub -t "/test" -m "test" --cafile ./ca.crt -p 8883 -h 127.0.0.1 -d
Client mosq-abdzCLL1ol2OBBbtvb sending CONNECT
Client mosq-abdzCLL1ol2OBBbtvb received CONNACK (0)
Client mosq-abdzCLL1ol2OBBbtvb sending PUBLISH (d0, q0, r0, m1, '/test', ... (4 bytes))
Client mosq-abdzCLL1ol2OBBbtvb sending DISCONNECT
```

Here is the outputs of `openssl x509 -text -noout -in ca.crt` :
```bash
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 12698842203822720606 (0xb03b59b3f997865e)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=DE, ST=Hessen, L=City, O=/emailAddress=
        Validity
            Not Before: Jul  8 16:00:28 2020 GMT
            Not After : Jul  8 16:00:28 2025 GMT
        Subject: C=DE, ST=Hessen, L=City, O=/emailAddress=
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b8:4e:aa:
```
Here is the outputs of `openssl x509 -text -noout -in server.crt`:
```bash
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 17023237616041219521 (0xec3eb06b373455c1)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=DE, ST=Hessen, L=City, O=/emailAddress=
        Validity
            Not Before: Jul  8 16:01:19 2020 GMT
            Not After : Jul  3 16:01:19 2021 GMT
        Subject: C=DE, ST=Hessen, L=City, O=, CN=127.0.0.1/emailAddress=
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:cc:b6:57:2
```

I initiate the connection:
```go
func connectToMqttBroker(c *configreader.Config) (*mqtt.Client, error) {
	//mqtt.DEBUG = log.New(os.Stdout, "", 0)
	mqtt.ERROR = log.New(os.Stdout, "", 0)

	

	opts := mqtt.NewClientOptions().AddBroker(c.GetMqttBrokerIp())
	opts.SetClientID(c.GetID() )

	tlsOptions := setTlsConfig(c.GetCaPath())
	opts.SetTLSConfig(tlsOptions)
	opts.SetAutoReconnect(true)

	opts.SetCleanSession(false)
	// creates a new client
	client := mqtt.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		return &client, token.Error()
	}

	return &client, nil
}

func setTlsConfig(caPath string) *tls.Config {
	// Get the SystemCertPool, continue with an empty pool on error
	rootCAs, _ := x509.SystemCertPool()
	if rootCAs == nil {
		rootCAs = x509.NewCertPool()
	}

	// Read in the cert file
	certs, err := ioutil.ReadFile(caPath)
	if err != nil {
		log.Fatalf("Failed to append %q to RootCAs: %v", caPath, err)
	}

	// Append our cert to the system pool
	if ok := rootCAs.AppendCertsFromPEM(certs); !ok {
		log.Println("No certs appended, using system certs only")
	}

	return &tls.Config{
		RootCAs: rootCAs,
	}
}
```

But I alway get following error by the [client]:
```bash
[client]   x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
[client]   Failed to connect to a broker
```

I dont see the reason of that problem. Perhabs it is caused by the empty CN of ca.crt but that should work too. If you use the same CN of ca.crt and server.crt the broker won't open a connection.

T

**Comment by MattBrittan** [comment]
[RFC 6125 notes](https://tools.ietf.org/html/rfc6125#appendix-B.2)

> In some cases, the URI is specified as an IP address rather than a hostname.  In this case, the iPAddress subjectAltName must be present in the certificate and must exactly match the IP in the URI.

The golang TLS library follows this standard (noting that the above quote is in a non-normative section) and does not allow the use of IP addresses [in the CN](https://golang.org/src/crypto/x509/verify.go#L1012); other implementations (e.g. whatever ```mosquitto_pub``` is using) aere more permissive.

So when using anything that relies on the golang TLS lib and the URI is an IP address then your certificate needs to include an IPSAN (as per the error message) or you can set ```InsecureSkipVerify: true``` in your ```tls.Config``` (in which case the certificate will not be validated). 

Note that your question is really about the standard golang TLS library (paho just calls ```tls.DialWithDialer``` passing in the ```tls.Config``` you set) so when searching for an answer for anything like this try removing MQTT from your search terms ([this goolge search](https://www.google.com/search?q=golang+IP+SANs&oq=golang+IP+SAN) pulls up heaps of relevant answers).

One further note; creating valid certificates can be a bit tricky with openssl so I suggest considering [certstrap]( https://github.com/square/certstrap) because it simplifies the process (and is written in go). A cert with the IPSAN you need can be requested with something like:

```
certstrap.exe init --years 20 -o Org -c NZ --common-name "Cert Auth MQTT"
certstrap request-cert -o Org -c NZ --ip 127.0.0.1 --common-name servername
certstrap sign servername --years 15 --CA "Cert Auth Chiot03 gRPC"
```

Matt
