### ISSUE TITLE
Add method to Token interface for getting pull-only channel

### ISSUE THREAD

**Issue by rittneje** [eclipse/paho.mqtt.golang#445]
The existing `Wait` and `WaitTimeout` methods on the `Token` interface are fairly inflexible. Since these are blocking calls, there is no way to stop waiting other than for it to succeed, fail, or timeout. For example, if I want to stop waiting upon context cancellation, there is no way to do it without leaking a goroutine.

```go
result := make(chan bool, 1)
go func() {
    result <- token.WaitTimeout(timeout)
}()

select {
case ok := <-result:
    ...
case <-ctx.Done():
    // There is no way to "abort" the goroutine above.
   return ctx.Err()
}
```

Instead, the `Token` interface should have a method for fetching the token's completion channel, which is closed when the operation in question succeeds or fails.

```go
type Token interface {
    ...
    Done() <-chan struct{}
}

ctx, cancelFunc := context.WithTimeout(ctx, timeout)
defer cancelFunc()

select {
case <-token.Done():
    return token.Error()
case <-ctx.Done():
    return ctx.Err()
}
```

**Comment by MattBrittan** [comment]
> For example, if I want to stop waiting upon context cancellation, there is no way to do it without leaking a goroutine.

For the timeout scenario your I don't believe that your code will leak a go-routine because `WaitTimeout` will return after `timeout` (and as the channel is buffered it will not block there). So the goroutine may run for a period after the context is cancelled but it will terminate eventually.

While I think its possible to achieve the result you are looking for with the current interface I agree that it's not ideal. There are a range of issues with the `Token` approach and the new [MQTT v5](https://github.com/eclipse/paho.golang) client uses a different approach (blocking calls which are passed a `Context`). Please feel free to submit a pull request for this change (I cannot guarantee that it would be accepted but from a quick look could not see any issues).

**Comment by rittneje** [comment]
Yes, the goroutine should exit upon the timeout, but as a matter of policy we do not allow functions to return without cleaning up their goroutines first.

I could also see just adding `WaitContext(context.Context) bool` as you alluded to. The only downside is it is a little less flexible, but it should at least suffice for our purposes.

**Comment by MattBrittan** [comment]
> I could also see just adding WaitContext(context.Context) bool as you alluded to. The only downside is it is a little less flexible, but it should at least suffice for our purposes.

Was not really suggesting that; in the v5 client the call to, for example, `Publish` takes a context and then blocks until the message has been sent or the context cancelled (there are no tokens at all). Given that we are stuck with Tokens in this version I think that getting a `channel` is a better option.
