### ISSUE TITLE
Invalid confirmation of success publish on reconnect

### ISSUE THREAD

**Issue by antlad** [eclipse/paho.mqtt.golang#458]
After successful reconnect `Token` interface indicates invalid delivery state of messages. Especially happen when ping to server is high. `Token` interface method `Wait` and then `Error` indicates - that there is no issues. But couple of first messages are not successfully delivered (QoS is 1). And we see gaps in data on other side with client that is continuously listen same topic without reconnects. But publisher don't see any errors from library.
Was tested with eclipse-mosquitto server and AWS IoT core.

**Comment by MattBrittan** [comment]
Can you please confirm which version of the package you are running. v1.2.0; is the most recent release but significant changes have been made since its release so I recommend using @master `go get github.com/eclipse/paho.mqtt.golang@master` (hopefully a new release will be made in the near future).

Your issue may be related to [this one](https://github.com/eclipse/paho.mqtt.golang/issues/442) which has been resolved (for me at least) but I was unable to identify the root cause (my attempt to generate traceable debug information ended up fixing the issue).

Assuming you are running the latest version I would appreciate some information to assist in tracking down the issue:

* Provide logs obtained when the issue is occurring (see my response on [this issue](https://github.com/eclipse/paho.mqtt.golang/issues/430) for instructions on enabling logging).
* Include a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) if possible (this package has a lot of options that can interact in unexpected ways so knowing your particular settings helps to track down the issue).

**Comment by antlad** [comment]
This issue was reproduced in 1.2.0 and with latest master (2 days ago). Ok, I'll try to grub logs.

**Comment by MattBrittan** [comment]
Thanks; please create the logs using `@master` (a lot of changes since 1.2.0 and more info is logged); it would also be helpful to have the Mosquitto logs (`log_type all`) for the test period. Of course if this is something that can be easily duplicated then the sample code is all that is needed (the package tests spin up Mosquitto using Docker).

**Comment by antlad** [comment]
@MattBrittan Sadly, I can't cut part of publisher. But I can give you access to test cloud receiver(with some changes on request). Attached logs from MQTT publisher and Mosquitto with `log_type all`. Test scenario:
- Publisher (in VirtualBox) is streaming data to remote Mosquitto server. Ping is ~40ms. Stream is 15 msgs/sec. QoS 1.
- On server side MQTT receiver is connected to Mosquitto server on same host(so no disconnects). Receiver publishing all data to InfluxDB(we tried AWS too) with timestamps that are produced by generator. QoS 1.
- From VirtualBox we emulate disconnect with `Cable Connected` checkbox. Wait for 1 minute and put it back to connected.

Disconnect happened from minutes ~28:30 to ~29:30 . As you see some of them are delivered, but not all.
![Screenshot 2020-10-26 at 10 31 59](https://user-images.githubusercontent.com/2556177/97149639-17f23700-177e-11eb-9f61-bed8ce74936a.png)

Issue happen probably on publisher side. We implement internal persistence layer, so we republish messages that are not delivered. But we didn't get any errors from MQTT library on `token.Error()` after `token.Wait()`.

[Archive.zip](https://github.com/eclipse/paho.mqtt.golang/files/5437660/Archive.zip)

**Comment by MattBrittan** [comment]
My analysis is below; unfortunately I did not find any issues based upon the information in the logs. In order to investigate further I would need to be able to replicate the issue so I’m afraid that I will need the code (just a minimal example; not your full code). Investigating these issues takes a considerable amount of time and can be very difficult/impossible without the ability to duplicate the issue (there is a limit to how much time I can dedicate to this). Your use of custom persistence makes this more difficult because I cannot identify which messages are missing from the logs (because the message IDs are reset when the connection is re-opened); implementing persistence correctly is a challenge (there have been a lot of fixes to the inbuilt persistence since v1.2.0).

I would suggest that the next step is for you to confirm if the issue is on the publish side (otherwise we may be looking in the wrong area!). The way I would approach this is to log the message IDs included in the tokens you receive from `Publish()` (use a type assertion to get a `PublishToken` and then call `MessageID()`) and compare this with the mosquitto log (the message IDs will be in both; note that mosquitto will use a different ID when sending the message to the subscriber). 

## Logs

The last message successfully transmitted/acknowledged before the outage was 1872:

```
Oct 26 07:28:20   --->[DEBUG] [store] memorystore del: message 1872 was deleted
Oct 26 07:28:20   --->[DEBUG] [net] startIncomingComms: received puback, id: 1872
```

```
1603697300: Received PUBLISH from golang-sdk (d0, q1, r0, m1872, 'topic_1', ... (249 bytes))
1603697300: Sending PUBACK to golang-sdk (m1872, rc0)
```

Messages 1873-2257 (at least - this is only logged in the net code) are published prior to the disconnection being detected (Oct 26 07:28:51/1603697331) - note that mosquitto does not detect the loss of connection (it only closes the connection when the client reconnects with the same ID).

Connection re-established at Oct 26 07:29:39/1603697379 (message IDs resume at 1).

```
Oct 26 07:29:40   --->[DEBUG] [client] enter Publish
Oct 26 07:29:40   --->[DEBUG] [client] sending publish message, topic: topic_1
Oct 26 07:29:40   --->[DEBUG] [net] obound msg to write 1
Oct 26 07:29:40   --->[DEBUG] [net] obound wrote msg, id: 1
```

```
1603697379: New connection from 188.134.82.147 on port 1883.
1603697379: Client golang-sdk already connected, closing old connection.
1603697379: New client connected from 188.134.82.147 as golang-sdk (p2, c1, k60).
1603697379: No will message specified.
1603697379: Sending CONNACK to golang-sdk (0, 0)
1603697380: Received PUBLISH from golang-sdk (d0, q1, r0, m1, 'topic_1', ... (249 bytes))
```

## Analysis

From the logs I think your configuration is:

* You are using `MemoryStore`
* `CleanSession` is true (from `c1` in Mosquitto log)

Based on that the process followed when the connection is lost is:

* `internalConnLost` is called and starts a go routing that:

   * shuts down the worker processes

   * calls `c.messageIds.cleanUp()` which sets the error state on all outstanding tokens (`token.setError(fmt.Errorf("connection lost before Publish completed"))`); this is happening `Oct 26 07:28:51   --->[DEBUG] [msgids] cleaned up`

   * sets the connection status `c.setConnected(disconnected)`
   * Calls the `OnConnectionLost` handler in a go routine

* Your `OnConnectionLost` handler does whatever it does (includes calling `Disconnect()` - `Oct 26 07:28:51   --->[WARN] [client] Disconnect() called but not connected (disconnected/reconnecting)`)

* Process to reconnect started (clears the memory store if its not already clear)

I cannot see any issues here that could lead to message loss (but there are quite a number of go routines involved so quite possible I'm missing something). I did think that messages may be stuck in `obound` but I can see from the logs that the routine that reads that is exiting (`Oct 26 07:28:51   --->[DEBUG] [client] startCommsWorkers output redirector finnished`) meaning that the publish should time out (unless you have set `WriteTimeout` to a large value).

**Comment by antlad** [comment]
@MattBrittan Thanks for so deep dive into. I'll try to prepare at morning separated example.

**Comment by antlad** [comment]
@MattBrittan I implemented standalone app doing almost similar work as in main app. But with auto-reconnect logic it is not reproducible. So will try to do same logic with manual connection state handling and double check our side.

**Comment by antlad** [comment]
@MattBrittan I added you to our testing app repo. We identified conditions when it happen. We want to have strong confidence on messages delivery and also high through put. So we using large amount of gorutines for waiting ack. Problem happen when when connection is restored and app try to publish many messages in parallel. Some of them receive success while it is not true. If you check our code - it is working in this default config, but if you change config like this:
![image (6)](https://user-images.githubusercontent.com/2556177/97542779-61d65980-19d8-11eb-950e-cf863b8cc77a.png)

it will lose some amount of messages on connection restore.
I can add you to receiving server (mqtt server, grubber and influx), let me know if you need it.

**Comment by MattBrittan** [comment]
Thanks @antlad. Please see my comments below. 

In summary I thought I had managed to duplicate your issue but it turned out to be a mosquitto configuration issue (which could possibly be the cause on your side). By default Mosquitto will queue 100 QOS1/QOS2 messages; after that messages are silently dropped; generally this is not something you will notice but when you have a large number of messages to send quickly (as happens when your application reconnects) you will loose data. Please check your `mosquitto.conf` for the `max_queued_messages` option; if it’s not there then this is your problem (I'm not sure if AWS IoT core has a similar setting). If not then further investigation will be needed.

If the above is not the solution then I will need to ask that you attempt to replicate the issue using the docker based test environment I have added to your repo (or something similar). As you may gather investigating these issues takes a lot of time and because there are multiple components involved I’m afraid that I will need a way to reliably replicate the problem without too much guesswork (while I’m keen to address any bugs in the package there is only so much time I can put into issues that do not impact my systems).

# Test Application Summary

Let me try and summarise what your application is doing (to help me remember if looking again):

***

You have `producersCount` * `w.producer` go routines adding messages every `produceInterval` to `publishQueue`, or, if the queue is full calling `w.persist(e)`. The messages include a value derived from the current time.

The `persist` messages are checked on a timer by `republishWorker` and resent to the queue (or stored back to the persistence layer if the send fails).

The `publishQueue` channel is drained by `workersCount` * `w.publisherJob`'s and keeps a count of the number of jobs it is waiting on (`w.waitingResponse`). It also keeps a count (`w.published`) of the number of messages successfully published.

The process runs until cancelled (with a signal) but does not wait for goroutines to cleanly exit.

***

The way you are reconnecting (reusing an existing `Client`) is not something I have tried previously (I use the inbuilt persistence and reconnect functionality); however I can't see any obvious that would cause it to fail. 2000 workers does not seem excessive (particularly as each thread is waiting for the previous one to finish).

I have spent a fair amount of time looking through your code and attempting to locate anything in the Paho library that would cause an issue without success.

# Testing

In an attempt to duplicate the issue I have created a rough environment in docker (uploaded to your repo in the `matt` folder). After bringing this up I can disconnect/reconnect from the network with `docker network disconnect lostpackets_test-net lostpackets_pub_1`/`docker network connect lostpackets_test-net lostpackets_pub_1`. 

The main change I have made to your test application is to add a message number to the JSON; this makes it simple to see what, if anything, has been lost.

While testing I let the number of  `persistence count` messages get up to over 6000 and then reconnected the network.

This led to the discovery of a small error in your code: `if t := cl.Connect(); t.WaitTimeout(time.Second) && t.Error() != nil {` should be `if t := cl.Connect(); !t.WaitTimeout(time.Second) || t.Error() != nil {` (otherwise the reconnect will not be re-attempted). After fixing this I tried again:

`workersCount`  = 2000; `republishChunk`  = 10

1. Started everything up and let some messages flow through
2. Cut the network connection to the publisher
3. Waited for `persistence count` to get over 5000 (got up to 6245)
4. Reconnected the network link
5. Waited for `persistence count`  to get down to 0
6. Stopped the containers
7. Sorted the `receivedMessages.txt` file and confirmed no missing lines (14055 messages received)

It was only after running this that I noticed that your screenshot had `republishChunk` set to 1000 and repeated the above process - `persistence count` got up to 4925. This run did result in lost messages (over 3000 of them). So it looks like there is an issue with the republish when sending a large number of messages very quickly.

## Narrow down cause

To confirm if the issue could be replicated by throwing a lot of messages at the broker very quickly I modified the application to preload 5000 messages and not generate any more. This replicated the issue - only 2400 messages were received. Further investigation revealed that the first 50-60 messages were being received but then there was a gap. Checked mosquitto documentation and found that the default for `max_queued_messages` is 100 ; the docs do not say so explicitly but it looks like messages over this are dropped silently. Reconfigured Mosquitto with `max_queued_messages 0` and the problem went away.

### Rerun test

Reran the test with `workersCount`  = 2000; `republishChunk`  = 5000 with the mosquitto setting `max_queued_messages 0` in place. 100% of messages were delivered.

**Comment by antlad** [comment]
@MattBrittan Thank you so much for helping with issue. Yes you are right - this is limit of ACK queue. We will make waiters pool configurable per cloud provider and it will solve problem. But it is a little bit weird if server just drop message without pub failed message, maybe worth to try check. But anyway I think we can close issue. Thank you!

**Comment by MattBrittan** [comment]
> But it is a little bit weird if server just drop message without pub failed message, maybe worth to try check

The [documentation ](https://mosquitto.org/man/mosquitto-conf-5.html )for `max_queued_bytes` does specifically say "Once this limit has been reached, subsequent messages will be silently dropped." so I think its safe to assume that the same applies to `max_queued_messages` which is immediately below it.

I think its important to remember that the broker is performing two quite separate operations here and this is a Pub/Sub arrangement (not a straight message queue):

1. It is receiving messages from a publisher. In this case that part of the process was working fine; all messages were received (and probably persisted) and the ACK sent back to the publisher.
2. Distribute the message to subscriber(s) (some of which may be offline). This is a separate step from the above; the broker will add the message to outgoing queues (1 queue per client), based upon subscriptions, and transmit them as it is able to. The speed at which messages are sent to subscribers will depend upon a number of factors (`max_inflight_messages` is a big one).

It makes sense that there is some limit to how many messages get queued for each client because otherwise the broker could easily become overloaded (however I would note that this is not something the [spec ](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html)addresses).

Either way from the perspective of the publisher (this library) there is nothing we can do; the message has been successfully transmitted to the broker and the broker has acknowledged this. The MQTT protocol does not provide any built in mechanism for confirming end-to-end delivery of messages (but generally with a correctly configured broker this is not an issue).

I do think that the fact that messages are being dropped could be more prominent in the Mosquitto logs...
