### ISSUE TITLE
Network Error "dial tcp 10.0.0.22:1883: i/o timeout exit status 1"

### ISSUE THREAD

**Issue by muhmdakml** [eclipse/paho.mqtt.golang#477]
Hi all, 

This is my first time posting to GitHub so do bear with my serious incompetency.
Following from this tutorial, https://gabrieltanner.org/blog/grafana-sensor-visualization , I'm trying to create a golang file with paho mqtt library to provide fake data to MQTT broker (and later visualise the data with Grafana). The golang file's name is :

`mqtt.go`

I've already installed : `go version go1.15.6 darwin/amd64`
and also installed :
`go get github.com/eclipse/paho.mqtt.golang`
`go get github.com/gorilla/websocket`
`go get golang.org/x/net/proxy`
And when I try to run : `go run mqtt.go`
The Mac Terminal's output : `network Error : dial tcp 10.0.0.22:1883: i/o timeout
exit status 1`

I'm pretty sure that means the golang file is unable to provide the data to MQTT data broker. But sadly, I don't know what I should do next. I tried switching off Firewall and also add 8.8.8.8 DNS but that didn't helped.

Any help is appreciated. Thanks!

**Comment by MattBrittan** [comment]
`dial tcp 10.0.0.22:1883: i/o timeout` means that a TCP connection with the MQTT broker could not be established. This is probably because there is not a broker listening on the IP address `10.0.0.22`. The tutorial does not mention where this address comes from as far as I can see (from a quick scan through); it seems to just assume that is the address in use (probably the address assigned to the authors PC). I'd try `127.0.0.1:1883` (loopback address - this should work if you are running the mosquitto container as per the tutorial). Note that I'd expect telegraph to be failing with the same issue (`127.0.0.1` will not work with that because its running in a container).

This repository includes [an example](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker) showing how to run Mosquitto/this library with docker; that's probably a good place to start.

Please note that we prefer that the issues section of this repository be used for reporting bugs rather than general requests for help using the library ([stack overflow](https://stackoverflow.com/questions/tagged/mqtt+go) is a better choice for requests like this because you are likely to get answers from others with experience using Grafana etc).

**Comment by muhmdakml** [comment]
Thank you so much for explaining the problem source in great detail. Yes I’ll try to modify the IP Address with another one and check if that resolves the problem. Kudos for linking the Mosquitto-Docker Repository too.

Again, thank you for the help and clarifying the purpose of Issues in GitHub. Will surely try stack overflow next time. 

BR
Muhd Akmal
