### ISSUE TITLE
doc or example on using persistence

### ISSUE THREAD

**Issue by sdeoras** [eclipse/paho.mqtt.golang#478]
Hi,

I am trying to use MQTT client with a persistence store and have not quite understood the workflow properly. In particular, my server on localhost is configured with persistence and I verified it as follows:
* Published several messages on a client id = myClientId and topic = myTopic with QoS = 2 (Go code using this library)
* As a second step, after publishing was done I ran following command: `mosquitto_sub -t myTopic -i myClientId -c -q 2`
* This returned all messages indicating persistence was working

I would like to configure such client side subscription behavior using this library and I am wondering if there is a documentation or an example code I can look at? Ultimately, I would like to test fail-over scenario of my clients without loss of messages.

Alternatively, what would be the command line options for the code in the link below that would allow me to publish several messages followed by a new command line execution for subscription that would pull all those previously published messages?
https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/sample/main.go 

Also it is not very clear to me if client side that is only subscribing and not publishing would require any persistence store?

Any help is appreciated. Thanks.

**Comment by MattBrittan** [comment]
Your steps are basically correct with one big caveat - this will not work the first time the client connects. Until a client connects (with[ cleansession](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194) set to 0/false) and subscribes (with QOS>0) to the topic the broker will not retain any messages. So the first step should be to connect and subscribe (you can then disconnect). 

I would recommend the [docker example](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker) because this highlights a few issues you may encounter (i.e. messages arriving before your subscribe is processed). 

>Also it is not very clear to me if client side that is only subscribing and not publishing would require any persistence store?
The memstore will be needed (but is used by default). You can probably get away without using disk but this may lead to you receiving duplicate messages. At QOS=2 there are four steps to sending a message (see (MQTT Essentials)[https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/]); if you handle a message but, for whatever reason, the PUBREC does not get through (e.g. your app shuts down) then the broker will resend the message.

Please note that this section is really for issues; as per the [readme ](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) we would appreciate it if you could direct questions (particularly those not specific to this package) elsewhere (MQTT questions on [stack overflow](https://stackoverflow.com/questions/tagged/mqtt) are generally answered quickly).

**Comment by sdeoras** [comment]
@MattBrittan thanks. it worked exactly as you described!
