### ISSUE TITLE
Very high CPU Load after a few hours

### ISSUE THREAD

**Issue by tobiasehlert** [eclipse/paho.mqtt.golang#491]
I'm author to a small Golang application inside a Docker container called TeslaMateApi.

In that application, I am using your library to connect to an MQTT broker to collect the latest published message of 46 topics. After a short sleep, I run a disconnect again and that's basically it.

I've received an issue from one of the users complaining that they are experiencing very high CPU load after using TeslaMateApi a few hours. And then it's only that particular endpoint doing the MQTT connection that has the issue.
Everything else is working just as expected, so I am wondering if you have some tip what we could do to resolve this somehow.

Here is a link to the file containing the MQTT part:
https://github.com/tobiasehlert/teslamateapi/blob/main/src/v1_TeslaMateAPICarsStatus.go

Here is a link to the issue:
https://github.com/tobiasehlert/teslamateapi/issues/8

**Comment by MattBrittan** [comment]
From the mosquitto logs it looks like `TeslaMateAPICarsStatusV1` is being called very rapidly:

```
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
```

After the restart this appears more as I would expect:

```
1615882448: New connection from 172.21.0.6 on port 1883.,
1615882448: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882448: Client teslamateapi disconnected.,
1615882458: New connection from 172.21.0.6 on port 1883.,
1615882458: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882458: Client teslamateapi disconnected.,
```

So, at first glance, it looks the issue might be something unrelated to MQTT (the `TeslaMateAPICarsStatusV1` is being called rapidly); this will lead to mosquitto disconnecting clients because they have the same client ID. It's worth noting that this function is not thread safe (its saving the data into global variables). Other than that I cannot see any obvious cause in this code but do have a few suggestions:

* It would be much nicer to subscribe once and cache incoming data (which can just be returned when the API call is made)
* If the above is not possible then a `sync.Once` to prevent multiple simultaneous executions...
* The code for subscribing/waiting is pretty fragile (would be better to subscribe and then wait until a timeout expires or the data has arrived)
* You are calling `m.Disconnect(250)` or `defer m.Disconnect(250)` (depending upon revision) from inside a loop but only connecting once (outside of the loop). You need to decide whether the connection should stay up for the whole loop or if a new connection should be established on each iteration (and using `defer` inside a loop is not really recommended!).

If someone wants to send me a Tesla I'll happily do some more testing :-).

**Comment by LelandSindt** [comment]
@MattBrittan if I had Oprah money I would send you a Tesla. :smile: 
![you get a car](https://user-images.githubusercontent.com/939903/111556343-505bd700-8758-11eb-948a-701f552c2fea.gif)

I agree with your first two points, and missed entirely the fact that the `m.Disconnect()` was inside a loop... I am testing after having moved it out/before the loop. 

Thank you for the insights.

**Comment by tobiasehlert** [comment]
Closing this issue, since we received awesome help from @MattBrittan!
Thanks for your valuable feedback, really appreciated 🥇
