### ISSUE TITLE
No republish for QoS>0 publish packets

### ISSUE THREAD

**Issue by ajatprabha** [eclipse/paho.mqtt.golang#511]
### Actual Behaviour
Steps
1. Client publishes a message with QoS 1
2. Packet is written on connection
3. Broker reads the Pub packet successfully but doesn't send PubAck back
4. This message with QoS 1 is not retried until next reconnection
5. The broker is actually not sending back PubAcks purposefully because it is in bad state and expects the client to retry the publish
6. Paho doesn't republish as mentioned in point 4
7. Broker is back in good shape
8. Next publish is successful(with incremented messageID) and PubAck is received

### Desired Behaviour
Steps
1. Client publishes a message with QoS 1
2. Packet is written on connection
3. Broker reads the Pub packet successfully but doesn't send PubAck back
4. This message should be retried again with some backoff until the PubAck is received without the need to reconnect

**Comment by MattBrittan** [comment]
By design this library should resend the `PUBLISH` packet when the connection is re-established (so long as `CleanSession` is FALSE). Your above steps don't mention any loss of connection so I'm guessing you are expecting the resend to be retried on a timer; this will not happen.

The [3.1 spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180916) is unclear on this (emphasis mine)

>When a Client reconnects with CleanSession set to 0, both the Client and Server MUST re-send any unacknowledged PUBLISH Packets (where QoS > 0) and PUBREL Packets using their original Packet Identifiers [MQTT-4.4.0-1]. This is the **only circumstance** where a Client or Server is **REQUIRED** to redeliver messages.

But [v5 spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Message_delivery_retry) is explicit:

>When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers **MUST NOT resend messages** at any other time 

So I believe the current approach is correct. It is worth noting that Mosquitto [changed from automatic resends](https://github.com/eclipse/mosquitto/blob/master/ChangeLog.txt) to this same approach. More info in [this stack overflow answer](https://stackoverflow.com/a/67594051/11810946).

Note that the spec does not require that message ID's increment (and it's only reasonably recently that this library was changed to behave in that way). All that is required is the the Message ID is not in use for another in-progress message.

**Comment by blackvirus18** [comment]
@MattBrittan Thanks for a detailed answer on this. Agree with the design of of not retrying the messages on a timer that would actually go against the basic design. But do you think the client should take care about returning an error in case PUBACK is not received within a certain deadline so that the application layer can have a retrial strategy for this scenario.

**Comment by MattBrittan** [comment]
It appears that you are trying to work around a non-compliant broker. [The spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718110) is pretty clear that if the broker gets into a "bad state" then it should close the connection:

>If the Client or Server encounters a Transient Error while processing an inbound Control Packet it MUST close the Network Connection on which it received that Control Packet [MQTT-4.8.0-2]. If a Server detects a Transient Error it SHOULD NOT disconnect or have any other effect on its interactions with any other Client.

So my first thought would be to look at what the broker is doing.

>But do you think the client should take care about returning an error in case PUBACK is not received within a certain deadline

As mentioned above the library should take care of this for you because the broker has an issue it should drop the connection if it encounters an issue. If you want to force a disconnection you can do this yourself (`Publish` returns a token; if it's not `Done` within your nominated time period call `Disconnect`). Resending messages without dropping the connection is technically within the 3.1 spec but could end up causing issues (such as duplicated messages at QOS2 and potentially message loss due to reuse of message IDs).

**Comment by ajatprabha** [comment]
Thank you for explanation and clarification. I'll be closing this issue now.
