### ISSUE TITLE
Messages silently dropped, token not returning error

### ISSUE THREAD

**Issue by Loris94** [eclipse/paho.mqtt.golang#527]
I've a mosquitto broker that is running in server behind a firewall. Ports needed are open and, from outside, I check that it's working with:
`mosquitto_sub  -h [ip address] -t "#" -u [username] -P [password] -v`
`mosquitto_pub  -h [ip address] -t "topic" -u [username] -P [password] -m "hello"`
and I can see the message is published. I'm having problems with another software using this library so I recreated the steps with this code:
```
package main

import (
    "crypto/tls"
    "fmt"
    "time"
    "strconv"
    MQTT "github.com/eclipse/paho.mqtt.golang"
)

func messageHandler(c MQTT.Client, msg MQTT.Message) {
    fmt.Printf("TOPIC: %s\n", msg.Topic())
    fmt.Printf("MSG: %s\n", msg.Payload())
}

func connLostHandler(c MQTT.Client, err error) {
    fmt.Printf("Connection lost, reason: %v\n", err)
}

func main() {

    opts := MQTT.NewClientOptions()

    skipVerify := true
    opts.AddBroker("tcp://[ip]:1883")
    opts.SetTLSConfig(&tls.Config{InsecureSkipVerify: skipVerify})
    opts.SetClientID("myclientid")
    opts.SetAutoReconnect(true)
    opts.SetCleanSession(true)
    opts.SetDefaultPublishHandler(messageHandler)
    opts.SetConnectionLostHandler(connLostHandler)

    opts.OnConnect = func(c MQTT.Client) {
        fmt.Printf("Client connected\n")
    }

    client := MQTT.NewClient(opts)
    token := client.Connect()
    token.Wait()
    fmt.Println("connected")
    if token.Error() != nil {
        fmt.Println("problems with connection")
        panic(token.Error())
    }
    for i := 0; i < 10; i++ {
        str := "hello: " + strconv.Itoa(i)
        token := client.Publish("topic/temperature", 0, false, str)
        token.Wait()
        if token.Error() != nil {
            fmt.Println("problems with pub")
        }
        fmt.Println("published")
        time.Sleep(1000 * time.Millisecond)
    }
    fmt.Println("finished")
    client.Disconnect(1)
}
```
The result I expected was to have every numbered hello published, but only few messages make it through. From the logs many `Connection lost, reason: EOF` and `Client connected` are printed, meaning it loses connection and reconnects. 
 I've done a similar script with python using the python paho mqtt library and it works flawlessly:
```
import paho.mqtt.client as mqtt
import time

topic1 = "topic/temperature"

mqttClient = mqtt.Client()

mqttClient.connect([ip], 1883, 60)
mqttClient.loop_start()
for i in range(10000):
    mqttClient.publish(topic1, "hello - " + str(i), qos= 0)
    #time.sleep(1)
mqttClient.loop_stop()
mqttClient.disconnect()
```
Both the codes are running on a raspberry pi. If I run the go one on my computer (which is in another location) it works better, there are not connections lost prints but it still drops some messages. I've also tried chaging QOS, but the results are similar.
This is my broker configuration file, I think it has the bare-minimum configurations to make it work:
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

log_dest file /var/log/mosquitto/mosquitto.log
log_type debug

allow_anonymous true

port 1883
listener 8883
```

**Comment by MattBrittan** [comment]
I would expect the code, as published here, to loose some messages. This is because it publishes 10 messages and then disconnects; the disconnect is likely to occur before the broker can send back copies of all of the messages. I'd suggest testing with a separate publisher & subscriber (see the [docker example](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker) for code).

Having said that the fact you are seeing network errors indicates that something else is going on. At QOS0 a disconnection/reconnection will result in loss of messages (because QOS0 really means fire-and-forget). I have seen similar issues that turned out to be due to [MTU](https://en.wikipedia.org/wiki/Maximum_transmission_unit) issues (the remote units in this case were connected via a private APN/VPN and the result was similar to what you are seeing - lowering the MTU solved this).

Unfortunately without more information (library version, logs) its difficult to help. I'd suggest that you tart by enabling logging in Mosquitto and checking if the messages are making it there (see the [readme](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) for instructions on enabling logging within this library).

**Comment by MattBrittan** [comment]
Note: I see you have opened a question on Stack overflow. Please direct all communication there; if you don't get a resolution (or it turns out the cause is a bug in this library) then the conversation can resume here (with more debugging info) but discussing this on two platforms simultaneously is wasteful.

**Comment by Loris94** [comment]
> One situation that would relate in similar symptoms to what you are seeing is if another client is connecting with the same client id (Mosquitto will drop existing connections with the same ID when the connection is established).

@MattBrittan It was exactly this, we had another machine running similar code that was using the same clientid.
Thanks for the detailed answer. I'll be closing the issue.
