### ISSUE TITLE
message broker

### ISSUE THREAD

**Issue by AHAOAHA** [eclipse/paho.mqtt.golang#562]
if there one client subscribe more than one broker servers, how can i know recved message from which borker server?

**Comment by MattBrittan** [comment]
As per the [readme](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) the issues section is intended for use reporting bugs rather than for requesting general assistance (other resources are suggested for that).

Quick answer - each client instance will only connect to a single broker (if you pass more then one in it will just connect to whichever first accepts the connection; this is really intended to allow for failover). So to establish connections to multiple brokers you will need multiple clients; so just assign different handlers (one way to do this is to use a closure that calls your generic handler but passes in an extra argument that indicates the broker).

**Comment by AHAOAHA** [comment]
thanks for your answer.
