### ISSUE TITLE
ESP8266 disconnects from AWS IoT on new message

### ISSUE THREAD

**Issue by audreylim** [eclipse/paho.mqtt.golang#587]
ESP8266 Client disconnects and reconnects when new message is published to topic on AWS IoT:

Retain: true
qos: 0

ESP8266 logs:
```
PubSubClient connecting to: {aws_endpoint}
Message received on topic_1: hello
PubSubClient connecting to: {aws_endpoint}
Message received on topic_1: hello2
```

Code:
```
void loop() {
  pubSubCheckConnect();
}

boolean reconnect() {
  if (pubSubClient.connect("clientID")) {
    Serial.println(" connected!!!");
    pubSubClient.subscribe("topic_1");
  }
  return pubSubClient.connected();
}

void pubSubCheckConnect() {
  if (!pubSubClient.connected()) {
     Serial.print("PubSubClient connecting to: "); Serial.print(awsEndpoint);
    long now = millis();
    if ((now - lastReconnectAttempt) > 500) {
      lastReconnectAttempt = now;
      if (reconnect()) {
        Serial.print("reconnect");
        lastReconnectAttempt = 0;
      }
    }
  } else {
    pubSubClient.subscribe("topic_1");
  }

  pubSubClient.loop();
}
```

Hoping to find out what's causing the disconnect to avoid the random soft WDT reset problem:

```
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: bearssl
sp: 3fff0088 end: 3fff0f
```

**Comment by MattBrittan** [comment]
You have raised this issue in `eclipse/paho.mqtt.golang` which is for the Paho MQTT client written in [Go](https://go.dev/); the source you have shared looks like C (so not Go)... Perhaps you meant to raise this [here](https://github.com/knolleary/pubsubclient)?

I'm closing this for now because the question does not appear to be relevant to this repository. If you believe this is incorrect then please edit the question and explain how this relates to the Go client.

**Comment by audreylim** [comment]
Correct, oops sorry!
