### ISSUE TITLE
How to get remote addr and local addr when connected

### ISSUE THREAD

**Issue by oyljerry** [eclipse/paho.mqtt.golang#595]
Hi All:  
    After mqtt is connected, is there any way to get remote address (IP:Port) and local address (IP:Port) from this library?  Thanks.

**Comment by oyljerry** [comment]
Thanks for reply.
Because I want to collect the information about current connection, So I want the remote address and local address.
"providing access would introduce some complexity because the library supports automatic reconnections" --> I think it can use a variable to store these, every time connected, refresh it. when disconnected, clear it.

**Comment by oyljerry** [comment]
@MattBrittan Is it ok to export `client.conn`, then others can use it to get more information about connection?

**Comment by MattBrittan** [comment]
No - it could not be accessed in a thread safe way (can be overwritten at any time by the reconnect code).

**Comment by oyljerry** [comment]
@MattBrittan  I checked [openConnection](https://github.com/eclipse/paho.mqtt.golang/blob/87173763ce056ff2dd4e61c01efae663539178e8/netconn.go#L40), I think here we just need to add a new callback and pass info(remoteAddr and localAddr) return conn in it. It seems reimplement **SetCustomOpenConnectionFn** is a bit duplicate.

**Comment by MattBrittan** [comment]
Implementing the connection function involves a little bit of copying/pasting but is easily done within your own code. I'm reluctant to add complexity to the library for a fairly niche requirement when there is a workaround (you have not explained what you are using this info for so it's difficult to see if it would be of use to anyone else).

**Comment by oyljerry** [comment]
I want this info is that the endpoint may have LB, and there are several IPs for it. So I want to get the remote addr and local addr of current MQTT connection. once more, It may be also useful when debug network issue.

**Comment by MattBrittan** [comment]
I'm going to close this issue. There is a fairly simple work around (implement your own [SetCustomOpenConnectionFn](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L443)) and capture the address you want in that (this should only take a couple of minutes to do). The reasons I'm not adding this to the library are:

* Cost/Benefit - Adding this will complicate the library and be used by a very small number of people. As there is a simple way of implementing this yourself the change is not worthwhile.
* Thread safety - the connection may be dropped/re-established at any time. This means that this feature would require further synchronisation and is unlikely to be all that useful (because the address info may change immediately after you have read it). The upshot of this is the feature would really need to be implemented as a callback (and an existing callback can easily be utilised to achieve the desired result).
