### ISSUE TITLE
Memory leak from goroutines stuck reading channels

### ISSUE THREAD

**Issue by umeat** [eclipse/paho.mqtt.golang#600]
I have an application which creates many MQTT clients. This application has a memory leak which I'm trying to diagnose. Looking at the heap pprof, I see that "runtime malg" appears to keep growing. Looking at the goroutine pprof, I see that there are a lot of goroutines from this library which are stuck reading from or writing to channels.

I've highlighted in this screenshot the goroutines which are spawned by calling `client.Disconnect(n)`. It _looks_ as though my mqtt Clients aren't correctly disconnecting and so the goroutines are stuck open.

Any suggestions for further troubleshooting this?

![image](https://user-images.githubusercontent.com/19561488/174004578-f0f3eebb-6a98-4c77-9fcd-1c84be588e96.png)

**Comment by MattBrittan** [comment]
Thanks for reporting this and sharing the profile; are you able to share any source?

Based on this I'd be looking at your `EMQXSourceService subscriber func2`; I have a feeling that you may be [blocking in a message handler](https://github.com/eclipse/paho.mqtt.golang#common-problems) (but do not have a lot of experience interpreting the profiler dumps). You might also consider trying `ClientOptions.SetOrderMatters(false)`.

Note that I'm not saying that this issue is in your code (I'm sure there are bugs in the library) but there do seem to be a log of go routines parked at that function.

**Comment by umeat** [comment]
Thanks for the suggestion. I obviously also don't have a lot of experience interpreting the profiles.

I'll have another more critical look at that function specifically, and post code if I get stumped again.

**Comment by umeat** [comment]
The issue was (of course) with my message handler function. There was a race condition which would lead it to blocking indefinitely some percentage of the time.

Thanks again.
