### ISSUE TITLE
can it support v5

### ISSUE THREAD

**Issue by shanjunmei** [eclipse/paho.mqtt.golang#604]
Another v5 dedicated client is too rudimentary

**Comment by MattBrittan** [comment]
Adding meaningful MQTT v5 support (i.e. supporting properties, actually adhering to the standard etc) to this package would require breaking changes. Given that breaking changes would be required it's much more sensible to move to the [new library](https://github.com/eclipse/paho.golang) offers a much simpler interface. As you say, that package does not yet offer full functionality (persistence) but I'd much rather invest any time there rather than updating this package (which has evolved over the years and become a lot more complex than it needs to be. If you want to add v5 support then please feel free to submit a PR (but it will be a lot of work). 
Closing this as a [duplicate](https://github.com/eclipse/paho.mqtt.golang/issues/347).
