### ISSUE TITLE
When to support quic protocol?

### ISSUE THREAD

**Issue by Gypsying** [eclipse/paho.mqtt.golang#608]
With the quic is developed，mqtt over quic is needed.
Will appreciated to got the release which support quic transport protocol.

**Comment by MattBrittan** [comment]
There are no plans to implement QUIC support (but pull requests would be considered).

This is probably something that could be done separately as a [CustomOpenConnectionFn](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetCustomOpenConnectionFn) if you are just using QUIC to establish a pipe. However QUIC has some overlap with MQTT (e.g. at-most-once message delivery guarantees) so implementation may be more involved. Until the major brokers support this (EMQX has an [experimental QUIC transport](https://www.emqx.io/docs/en/v5/advanced/quic.html)) I'm not even sure what QUIC support would look like.

**Comment by Gypsying** [comment]
> There are no plans to implement QUIC support (but pull requests would be considered).
> 
> This is probably something that could be done separately as a [CustomOpenConnectionFn](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetCustomOpenConnectionFn) if you are just using QUIC to establish a pipe. However QUIC has some overlap with MQTT (e.g. at-most-once message delivery guarantees) so implementation may be more involved. Until the major brokers support this (EMQX has an [experimental QUIC transport](https://www.emqx.io/docs/en/v5/advanced/quic.html)) I'm not even sure what QUIC support would look like.

Thanks for your reply!

Maybe can integrate with the [quic-go](https://github.com/lucas-clemente/quic-go)? 
There has a implementation: [Evaluation of QUIC in Industrial IoT Scenarios ](https://pdfs.semanticscholar.org/9c86/6f66ea40cce43518bbf81ed670121c671726.pdf) which used the quic-go to implement the quic protocol;
Open and close connections, or send and receive packets, are managed by [paho.mqtt.golang](https://github.com/eclipse/paho.mqtt.golang)'s net.go interface.

[paho.mqtt.golang](https://github.com/eclipse/paho.mqtt.golang) just need to involve minor changes to support quic connection.

**Comment by MattBrittan** [comment]
Anyone is most welcome to add support via [SetCustomOpenConnectionFn](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetCustomOpenConnectionFn). I feel that cost of accepting this into the main library (complexity, impact on executable sizes, increase in dependencies etc) currently outweighs the benefits (note that the [report authors fork](https://github.com/pgOrtiz90/paho.mqtt.golang) does exactly that and should be relatively simple to adapt). This may change if QUIC becomes something supported by a range of brokers and the benefits become more apparent (currently this is probably of most interest to those pushing a high volume of messages over poor quality links).

Note that I would be happy to create a folder off the main project to contain new custom open connection functions so that these are available to all users (I feel this provides 95% of the benefits of implementing these within the library without any of the disadvantages of doing so).

**Comment by Gypsying** [comment]
Yes, you are right,
Support custom connection would be a more appropriate method.
I will have a look [SetCustomOpenConnectionFn](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetCustomOpenConnectionFn), thanks!
