### ISSUE TITLE
hangs on internalConnLost func

### ISSUE THREAD

**Issue by Gypsying** [eclipse/paho.mqtt.golang#621]
https://github.com/eclipse/paho.mqtt.golang/blob/2d3b04d5b874851cf7e76f51987492393c88e258/client.go#L520

I used [2d3b04d5b874851cf7e76f51987492393c88e258](https://github.com/eclipse/paho.mqtt.golang/commit/2d3b04d5b874851cf7e76f51987492393c88e258) version which commit on Dec 28, 2021.

Sometimes the client will **hangs** after `pingresp not received, disconnecting`, i use pprof inspect: 

![image](https://user-images.githubusercontent.com/17995262/204699782-dcd26e8d-b7bc-4648-b470-a8376fa664b5.png)

![image](https://user-images.githubusercontent.com/17995262/204699345-cc5771f5-6b65-478a-9d33-118b5b7e6224.png)

any ideas? @MattBrittan

**Comment by MattBrittan** [comment]
Can you please try the latest release? That release fundamentally changes the way the connection status is handled replacing some very old code. Further work needed to tidy things up (there is some code to try to work around the previous deficiencies that should not longer be needed) but the change made removes a few potential deadlocks (so I'm reluctant to spend much time on older releases).

However, in this case, my guess is that the issue is within your message handler. The library will not complete the shutdown until handlers return and your dump shows that the library is waiting on a handler ([here](https://github.com/eclipse/paho.mqtt.golang/blob/2d3b04d5b874851cf7e76f51987492393c88e258/router.go#L214)) so I believe that is most likely to be the issue (see the third point in [common issues](https://github.com/eclipse/paho.mqtt.golang#common-problems)).

**Comment by Gypsying** [comment]
> Can you please try the latest release? That release fundamentally changes the way the connection status is handled replacing some very old code. Further work needed to tidy things up (there is some code to try to work around the previous deficiencies that should not longer be needed) but the change made removes a few potential deadlocks (so I'm reluctant to spend much time on older releases).
> 
> However, in this case, my guess is that the issue is within your message handler. The library will not complete the shutdown until handlers return and your dump shows that the library is waiting on a handler ([here](https://github.com/eclipse/paho.mqtt.golang/blob/2d3b04d5b874851cf7e76f51987492393c88e258/router.go#L214)) so I believe that is most likely to be the issue (see the third point in [common issues](https://github.com/eclipse/paho.mqtt.golang#common-problems)).


Thanks your reply, i used the latest release([v1.4.2](https://github.com/eclipse/paho.mqtt.golang/releases/tag/v1.4.2)).
And the trouble does not appear again, the client is running very well for 5days up to now.

Maybe the old releases has a few potential deadlocks  like you said.

Thanks again!
