### ISSUE TITLE
`github.com/gorilla/websocket` Depreciated - Should we move to an alternative (and, if so, what)

### ISSUE THREAD

**Issue by zhoub** [eclipse/paho.mqtt.golang#627]
Hi,

Since https://github.com/gorilla/websocket was archived, I think it's best to switch to https://pkg.go.dev/golang.org/x/net/websocket .

Thanks in advance.

**Comment by MattBrittan** [comment]
Based upon [this issue](https://github.com/golang/go/issues/18152) I believe that `golang.org/x/net/websocket` is effectively depreciated as well. There is an open PR #583 (issue #585)  that moves to [` nhooyr/websocket`](https://github.com/nhooyr/websocket) but I was reluctant to accept this because it led to a 12% increase (around 800kb) in the size of a test app with no real benefit (webassembly should be able to be supported using `ClientOptions.SetCustomOpenConnectionFn`).

I'm interested in feedback on this - will change the title of your post to make it clear that this is a broader discussion and see if anyone else has thoughts..

**Comment by lxzan** [comment]
try https://github.com/lxzan/gws , provide better performance, easier to use API

**Comment by bmarinov** [comment]
No longer deprecated :) see https://gorilla.github.io/blog/2023-07-17-project-status-update/
o/

**Comment by MattBrittan** [comment]
Closing this as the Gorilla libraries are now being maintained again.
