### ISSUE TITLE
EOF error if client is already connected..

### ISSUE THREAD

**Issue by rakesh-eltropy** [eclipse/paho.mqtt.golang#63]
Hi,

I am using following code to create new client:

```
func CreateMQTTClient(clientID string) (client MQTT.Client) {
    username := viper.GetString("messaging.rabbitmq.username")
    password := viper.GetString("messaging.rabbitmq.password")
    host := viper.GetString("messaging.rabbitmq.host")
    mqqtPort := viper.GetString("messaging.rabbitmq.mqqtPort")
    rabbitMqMQQTURL := "tcp://" + host + ":" + mqqtPort
    opts := MQTT.NewClientOptions().AddBroker(rabbitMqMQQTURL)
    opts.SetClientID(clientID)
    opts.Username = username
    opts.Password = password
    opts.SetCleanSession(false)
    opts.ProtocolVersion=4
    opts.OnConnect=OnConnectHandler
    opts.AutoReconnect = true
    opts.OnConnectionLost = OnConnectionLostHandler
    cli := MQTT.NewClient(opts)

    log.Println(cli.IsConnected())

    token := cli.Connect()
    token.Wait()
    if token.Error() != nil {
        log.Print(token.Error())
    }


    return cli

}
```

Since there is no way for me to get existing client and check if client already exists for given client Id. If I call this function again, I am getting EOF exception and OnConnectHandler, OnConnectionLostHandler are being called forever until I kill golang server. It is happening only if AutoReconnect is true.

**Comment by alsm** [comment]
To be clear if you create two clients with the same clientid and autoreconnect set to true both end up looping calling OnConnectHandler and onConnectionLostHandler? I'm afraid this is expected behaviour, each client instance is separate from all others there is no way to know from a client point of view from the server if a client id is already in use on the server. MQTT allows for the takeover of a client id, in this case the currently connected client will be disconnected by the server so the second can continue the session (useful if the connection drops in an unclean way).
If you really need persistent sessions you will need to find a way to generate unique client ids.

**Comment by alsm** [comment]
Closing as no further response
