### ISSUE TITLE
client.Connect() after client.Disconnect() doesnt work for persistent session

### ISSUE THREAD

**Issue by ericfonseca** [eclipse/paho.mqtt.golang#64]
If I start a durable client connection (setCleanSession = false) and I disconnect, then try to reconnect with the same client I don't receive any messages. The publish and subscribe are done with QOS1. 

My suspicion is that on client disconnect the stopRouter chan is closed and it is not reopened on connect.

If i add these lines above line 233 in client.go my session resumes just fine.

		c.msgRouter, c.stopRouter = newRouter()
		c.msgRouter.setDefaultHandler(c.options.DefaultPublishHander)
		if !c.options.AutoReconnect {
			c.options.MessageChannelDepth = 0
		}

**Comment by alsm** [comment]
This is probably a bad choice I made to fix leaking goroutines, the assumption in the client is that when you call Disconnect() manually you are finished and done with that client, but I didn't make that clear because you still have a valid pointer to a Client after calling it.
My instinct would be to change the code so this is the case (that shouldn't really break anyone because, as you have found out, you can't properly reconnect a Disconnect()ed client), and I wouldn't want to start leaking goroutines for people who have used it this way and I'm not keen to make a breaking API change for this at the moment.
Thoughts?

**Comment by ericfonseca** [comment]
I was thinking along the same lines and struggled to find a case where a user would deliberately disconnect only to reconnect later. Maybe a system with a dynamic number of open connections based on network performance? All you need is the clientID to resume the durable connection so using the same client is not necessary, so I agree with you. Still something about the method being called Disconnect doesn't really reflect the fact that the client will be unusable after. All in all, I see your points and having a reconnectable closed client is worth leaking goroutines. Thanks for taking the time to explain :)
