### ISSUE TITLE
Dual Licensing EDL 1.0

### ISSUE THREAD

**Issue by juliuskluge** [eclipse/paho.mqtt.golang#644]
Can we please add the EDL 1.0 license to the LICENSE file for processing dual licensing better? Currently there is only the EPL 2.0 in the LICENSE file, which is used by most classifiers to determine the used license. Therefore the parser we use at our organisation can not detect the EDL 1.0 license, which we need to specify in order to use the library.

**Comment by MattBrittan** [comment]
I took the current approach because of difficulties with the [pkg.go.dev]https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang(https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang) [license check](https://pkg.go.dev/license-policy) (as per the notes in the file). If you can confirm that your PR passes their check (i.e. documentation will still be viewable) then I'll happily accept it (but really don't want to break `[pkg.go.dev]https://pkg.go.dev) support.

**Comment by juliuskluge** [comment]
Thanks for the quick response. I don't think it will pass the check as the EDL-1.0 is not listet in [license check](https://pkg.go.dev/license-policy). I will close the PR and will choose a different approach.
