### ISSUE TITLE
Understanding DUP messages, and manually set DUP flag.

### ISSUE THREAD

**Issue by Kushagra0409** [eclipse/paho.mqtt.golang#649]
As per my understanding, DUP flags are sent from the sender (publisher) to the receiver (broker) in QOS1, when it (sender) does not receive acknowledgement in form of PUBACK packet. So the same message is re-sent to the broker with DUP set to true. 
But do we have any option or functionality to not send these Duplicate messages forward? Please help me understand the overall use of DUP flags, as it seems to be completely ignored in handling of such messages. Also, for testing purposes, is there any way to manually set DUP flag to true from the MQTT client itself?

**Comment by MattBrittan** [comment]
This is not really the place for general MQTT questions - one of the resources mentioned in the [readme](https://github.com/eclipse/paho.mqtt.golang#more-information) is probably more appropriate. Alternatively the [specs](https://mqtt.org/mqtt-specification/) are quite readable, or there are heaps of guides (e.g. [this](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/)).

The DUP flag should be set whenever a PUB packet is retransmitted (with MQTT v5 this only occurs upon connection, with V3 it is permitted to happen at other times but most brokers now follow the v5 rules). Unfortunately the receiver cannot really make much use of this flag because it may, or may not, have received it when it was sent previously (so it's really only an indication that it's worth checking if the packet has been handled previously). At QOS1 doing this requires info outside of that provided by the protocol (e.g. check database to see if the record is there). As QOS2 we can check if we have sent a PUBREL (should be in the session).

You may find my [current work](https://github.com/ChIoT-Tech/paho.golang/blob/store/paho/session/state/state.go#L30) implementing this in the v5 client of interest.

**Comment by MattBrittan** [comment]
I'm going to close this as I believe it was a question, which I have answered.
