### ISSUE TITLE
32 bit bullseye and paho-mqtt 2.0

### ISSUE THREAD

**Issue by jimmusson** [eclipse/paho.mqtt.golang#668]
the statement "client = mqtt.Client()" fails.  rollback to 1.6.1 fixes it.

**Comment by MattBrittan** [comment]
I think you have logged this on the wrong repo; this is a Go client and your issue (I'm guessing) looks like it's with the newly released v2 [Python client](https://github.com/eclipse/paho.mqtt.python) (as the version numbers match up). 

As such I'm going to close this issue here; please feel to add details if I'm incorrect or log an issue on the correct repo (but please include more information; i.e. what does "fails" actually mean, provide an example etc).

**Comment by jimmusson** [comment]
Ok, sorry about that!

Jim Musson
Digital Computer Services
105 W King St Suite 201
Hillsborough NC 27278
***@***.******@***.***>
