### ISSUE TITLE
Incorrect/misleading copyright notices in `client.go`

### ISSUE THREAD

**Issue by ryanworl** [eclipse/paho.mqtt.golang#684]
There is a copyright notice in the repository that is incorrect. It was added in this commit: https://github.com/eclipse/paho.mqtt.golang/commit/ef66e71b0c5d228c9102f87400ff54a60bc9f0da

https://github.com/eclipse/paho.mqtt.golang/blob/714f7c0231294ec4144f0e0e5fc5b43a6d430d2f/client.go#L20

Can this be removed from this repository please? I'm happy to contribute the PR myself if necessary, but wanted to make sure that the maintainers are all on the same page that this notice is incorrect. The contributors to this repository sign a CLA that assigns copyright to the Eclipse Foundation. This requirement was present at the time of the contribution as well: https://github.com/eclipse/paho.mqtt.golang/blob/7fc2769689a3372ec1f7fd9c127807d36af75982/CONTRIBUTING.md

**Comment by MattBrittan** [comment]
> but wanted to make sure that the maintainers are all on the same page that this notice is incorrect. 

I'm not sure if I am :-). The ECA states:

>You still own Your Contributions, and except for the licenses provided for in this ECA, You reserve all right, title and interest in Your Contribution

and 

>You grant a non-exclusive, worldwide, perpetual, royalty-free license of all necessary rights under Your copyright in and to Your Contributions 

So I'm not sure that this copyright statement is an issue? I'm happy to be corrected on this but it's something we would need to run through the Eclipse licensing team (mailto:license@eclipse.org) before making a change (I don't know that we could remove the copyright without also removing the contributed code).

Note that with the V5 client I moved to the more generic header "Copyright (c) 2024 Contributors to the Eclipse Foundation" because I felt that this is clearer.

**Comment by ryanworl** [comment]
Thanks for your quick attention on this. It looks like you're correct, and I was thinking of another organization's CLA requiring assignment instead of granting a license.
